Repository intel/neural-compressor, pull requests merged in 2022-11, with the labels that each got.

#136 Update docstrings for some experimental files
  neural_compressor/experimental/common/torch_utils.py
  neural_compressor/experimental/component.py
  neural_compressor/experimental/data/__init__.py
  neural_compressor/experimental/data/datasets/bert_dataset.py
  neural_compressor/experimental/data/datasets/coco_dataset.py
  neural_compressor/experimental/data/datasets/dataset.py
  neural_compressor/experimental/data/filters/__init__.py
  neural_compressor/experimental/data/filters/coco_filter.py
  neural_compressor/experimental/data/filters/filter.py
Labels: documentation

#139 Add new quantization document
  docs/Quantization.md
  docs/imgs/PTQ.png
  docs/imgs/QAT.png
  docs/imgs/accuracy_aware_tuning_flow.png
  docs/imgs/dynamic_quantization.png
  docs/quantization.md
Labels: documentation

#141 Fix invalid link in README
  README.md
Labels: documentation

#158 add DocString for SelfKnowledgeDistillation
  neural_compressor/experimental/common/criterion.py
Labels: documentation

#151 support pydocstyle check
  .azure-pipelines/code-scan.yml
  .azure-pipelines/docker/DockerfileCodeScan.devel
  .azure-pipelines/scripts/codeScan/bandit/bandit.sh
  .azure-pipelines/scripts/codeScan/pydocstyle/pydocstyle.sh
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  neural_compressor/experimental/common/__init__.py
  neural_compressor/experimental/pruning.py
Labels: pending, validation

#146 Enable dilated contraction fusion for ITEX
  neural_compressor/adaptor/tf_utils/graph_rewriter/generic/pre_optimize.py
Labels: new feature

#160 Enable QDQ-adapted _QuantizedFusedBatchNorm+LeakyRelu fusion
  .azure-pipelines/scripts/ut/env_setup.sh
  neural_compressor/adaptor/tensorflow.yaml
  neural_compressor/adaptor/tf_utils/quantize_graph/qdq/fuse_qdq_bn.py
  neural_compressor/adaptor/tf_utils/quantize_graph/quantize_graph_bn.py
  test/tfnewapi/test_tensorflow_graph_qdq_bn_fusion.py
Labels: new feature

#168 fix ipex quantization
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#147 Enable _MklFusedBatchMatMulV2 BF16 conversion
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tensorflow.yaml
  neural_compressor/adaptor/tf_utils/graph_converter.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/bf16/bf16_convert.py
Labels: new feature

#175 Pruning doc refinements
  docs/source/pruning.md
  docs/source/validated_model_list.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/pytorch_pruner/eager/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/pytorch_pruner/eager/bert_mini_mrpc_1xchannel.yaml
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/pytorch_pruner/eager/bert_mini_sst2_1xchannel.yaml
Labels: documentation
