Repository intel/neural-compressor, pull requests merged in 2022-12, with the labels that each got.

#210 Fix NTM-One-Shot failed with KeyError
  neural_compressor/adaptor/tf_utils/graph_rewriter/generic/pre_optimize.py
Labels: extension test

#213 [Strategy] Adjust the hints for import hyperopt and sigopt
  neural_compressor/contrib/strategy/sigopt.py
  neural_compressor/contrib/strategy/tpe.py
  test/requirements.txt
Labels: enhancement

#209 modify Model-Test pipeline
  .azure-pipelines/model-test.yml
  .azure-pipelines/scripts/models/collect_log_all.py
  .azure-pipelines/scripts/models/collect_log_model.py
  .azure-pipelines/scripts/models/generate_report.sh
Labels: validation

#195 New Export with API 2.0
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/config.py
  neural_compressor/experimental/__init__.py
  neural_compressor/experimental/export/__init__.py
  neural_compressor/experimental/export/torch2onnx.py
  neural_compressor/experimental/export/utils.py
  neural_compressor/model/torch_model.py
  test/export/test_torch2onnx.py
Labels: new feature, extension test

#242 Fix ITEX OOB model benchmark issue
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
Labels: bug fix

#239 Updated multi-nodes distillation results of MobileNetV2-0.35 and CNN-2 examples
  docs/source/validated_model_list.md
Labels: documentation

#231 Enhance ITEX benchmark UT check
  test/itex/test_tensorflow_itex_basic.py
Labels: enhancement

#216 Fix Windows multi-instance bug
  examples/.config/model_params_onnxrt_win.json
  neural_compressor/experimental/benchmark.py
Labels: bug fix, extension test

#247 update spell check dict
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
Labels: validation

#252 azure ut basic fix
  .azure-pipelines/scripts/ut/collect_log.sh
  .azure-pipelines/ut-basic.yml
  .azure-pipelines/ut-ncoder.yml
Labels: review, validation

#230 Add hawq_v2 tuning strategy
  examples/.config/model_params_pytorch.json
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/conf.yaml
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/hawq_metric.py
  neural_compressor/conf/config.py
  neural_compressor/config.py
  neural_compressor/strategy/hawq_v2.py
  neural_compressor/strategy/utils/tuning_sampler.py
  test/strategy/test_hawq_v2_2.x.py
Labels: new feature

#251 Fixed pruning and distillation bug and remove invalid code
  docs/source/dataloader.md
  docs/source/dataset.md
  neural_compressor/__init__.py
  neural_compressor/experimental/common/criterion.py
  neural_compressor/experimental/distillation.py
  neural_compressor/quantization.py
  neural_compressor/training.py
  test/distillation/test_distillation.py
  test/metric/test_register_metric_transform.py
  test/quantization/test_quantization.py
Labels: enhancement, review

#243 add keras-in/keras-out to INC
  .azure-pipelines/scripts/ut/env_setup.sh
  .azure-pipelines/scripts/ut/run_basic_itex.sh
  examples/keras/mnist/README.md
  examples/keras/mnist/mnist.py
  examples/keras/mnist/requirements.txt
  neural_compressor/adaptor/keras.py
  neural_compressor/adaptor/keras.yaml
  neural_compressor/adaptor/keras_utils/__init__.py
  neural_compressor/adaptor/keras_utils/quantizer.py
  neural_compressor/conf/config.py
  neural_compressor/conf/pythonic_config.py
  neural_compressor/experimental/benchmark.py
  neural_compressor/experimental/common/model.py
  neural_compressor/experimental/component.py
  neural_compressor/experimental/data/dataloaders/dataloader.py
  neural_compressor/experimental/metric/metric.py
  neural_compressor/model/keras_model.py
  neural_compressor/model/model.py
  neural_compressor/strategy/strategy.py
  test/itex/test_keras_in_keras_out.py
Labels: new feature

#236 add warning when meets unsupported config
  neural_compressor/strategy/utils/tuning_space.py
  test/strategy/test_tuning_space.py
Labels: enhancement

#258 use local cached model for dynas ut test
  .azure-pipelines/scripts/ut/run_basic_others.sh
  .azure-pipelines/ut-basic.yml
  .azure-pipelines/ut-ncoder.yml
  .azure-pipelines/ut-ux.yml
  test/itex/test_tensorflow_itex_basic.py
Labels: bug fix

#224 Export Qlinear to QDQ
  neural_compressor/adaptor/ox_utils/operators/__init__.py
  neural_compressor/adaptor/ox_utils/operators/activation.py
  neural_compressor/adaptor/ox_utils/operators/argmax.py
  neural_compressor/adaptor/ox_utils/operators/attention.py
  neural_compressor/adaptor/ox_utils/operators/binary_op.py
  neural_compressor/adaptor/ox_utils/operators/concat.py
  neural_compressor/adaptor/ox_utils/operators/conv.py
  neural_compressor/adaptor/ox_utils/operators/direct_q8.py
  neural_compressor/adaptor/ox_utils/operators/embed_layernorm.py
  neural_compressor/adaptor/ox_utils/operators/gather.py
  neural_compressor/adaptor/ox_utils/operators/gavgpool.py
  neural_compressor/adaptor/ox_utils/operators/gemm.py
  neural_compressor/adaptor/ox_utils/operators/matmul.py
  neural_compressor/adaptor/ox_utils/operators/maxpool.py
  neural_compressor/adaptor/ox_utils/operators/ops.py
  neural_compressor/adaptor/ox_utils/operators/pad.py
  neural_compressor/adaptor/ox_utils/operators/pooling.py
  neural_compressor/adaptor/ox_utils/operators/resize.py
  neural_compressor/adaptor/ox_utils/operators/split.py
  neural_compressor/config.py
  neural_compressor/experimental/export/__init__.py
  neural_compressor/experimental/export/qlinear2qdq.py
  neural_compressor/model/onnx_model.py
  test/export/test_onnx_qlieanr_to_qdq.py
Labels: new feature

#219 Refine Keras Examples for INC New API
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_tensorflow.json
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/inception_v3.yaml
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/inception_v3_itex.yaml
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/mobilenet_v2.yaml
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/mobilenet_v2_itex.yaml
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/resnet101.yaml
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/resnet101_itex.yaml
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/resnetv2_101.yaml
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/resnetv2_101_itex.yaml
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/resnetv2_101/quantization/ptq/run_tuning.sh
Labels: examples, extension test

#276 update partial NVidia A100 CUDA EP ONNX QDQ accuracy data
  docs/source/validated_model_list.md
Labels: documentation

#174 INC new API tensorflow examples update
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_tensorflow.json
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/inception_resnet_v2.yaml
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/inception_resnet_v2_itex.yaml
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/resnetv2_50.yaml
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/resnetv2_50_itex.yaml
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/resnetv2_50/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/xception.yaml
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/xception_itex.yaml
  examples/tensorflow/image_recognition/resnet_v2/quantization/qat/resnet_v2.py
Labels: examples, extension test

#287 Fix onnxrt numpy round bug
  neural_compressor/adaptor/ox_utils/util.py
Labels: bug fix

#300 update numpy dtype
  .azure-pipelines/scripts/models/env_setup.sh
  .azure-pipelines/scripts/ut/env_setup.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/utils_qa.py
  examples/onnxrt/object_detection/onnx_model_zoo/DUC/quantization/ptq/main.py
  examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq/main.py
  examples/pytorch/nlp/huggingface_models/common/examples/question-answering/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/distillation/eager/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/pattern_lock/eager/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/pytorch_pruner/eager/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/utils_qa.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/magnitude/eager/callback/trainingmonitor.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/maskrcnn_benchmark/modeling/rpn/anchor_generator.py
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/utils.py
  neural_compressor/data/datasets/dummy_dataset_v2.py
  neural_compressor/experimental/data/datasets/dummy_dataset_v2.py
  neural_compressor/experimental/metric/coco_tools.py
  neural_compressor/metric/coco_tools.py
  neural_compressor/strategy/bayesian.py
  test/adaptor/tensorflow_adaptor/test_tensorflow_graph_matmul_fusion.py
  test/adaptor/tensorflow_adaptor/test_tensorflow_grappler_pass.py
  test/tfnewapi/test_tensorflow_fuse_reshape_transpose.py
  test/tfnewapi/test_tensorflow_graph_qdq_matmul_fusion.py
Labels: bug fix

#272 Refine tf_examples with INC User NewAPI
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  examples/README.md
  examples/helloworld/README.md
  examples/helloworld/tf_example1/README.md
  examples/helloworld/tf_example1/conf.yaml
  examples/helloworld/tf_example1/requirements.txt
  examples/helloworld/tf_example1/test.py
  examples/helloworld/tf_example2/README.md
  examples/helloworld/tf_example2/conf.yaml
  examples/helloworld/tf_example2/requirements.txt
  examples/helloworld/tf_example2/test.py
  examples/helloworld/tf_example3/README.md
  examples/helloworld/tf_example3/conf.yaml
  examples/helloworld/tf_example3/requirements.txt
  examples/helloworld/tf_example3/test.py
  examples/helloworld/tf_example4/README.md
  examples/helloworld/tf_example4/conf.yaml
  examples/helloworld/tf_example4/requirements.txt
  examples/helloworld/tf_example4/test.py
  examples/helloworld/tf_example5/README.md
  examples/helloworld/tf_example5/conf.yaml
  examples/helloworld/tf_example5/requirements.txt
  examples/helloworld/tf_example5/test.py
  examples/helloworld/tf_example6/README.md
  examples/helloworld/tf_example6/conf.yaml
  examples/helloworld/tf_example6/requirements.txt
  examples/helloworld/tf_example6/test.py
  examples/helloworld/tf_example7/README.md
  examples/helloworld/tf_example7/requirements.txt
  examples/helloworld/tf_example7/test.py
  examples/helloworld/tf_example8/README.md
  examples/helloworld/tf_example8/requirements.txt
  examples/helloworld/tf_example8/test.py
Labels: examples, extension test

#309 Fix failed `test_run_sigopt_one_trial_new_api`
  test/strategy/test_sigopt.py
Labels: bug fix

#261 Fixed some bugs for mse_v2 strategy
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/experimental/quantization.py
  neural_compressor/strategy/mse.py
  neural_compressor/strategy/mse_v2.py
  neural_compressor/strategy/utils/__init__.py
  neural_compressor/strategy/utils/helper.py
Labels: bug fix

#290 Remove Documents of GraphOptimization and ModelConversion
  README.md
  docs/source/Welcome.md
  docs/source/api-documentation/component/ModelConversion.rst
  docs/source/graph_optimization.md
  docs/source/model_conversion.md
Labels: documentation, review

#299 Fix DLRM OOM issue
  examples/pytorch/recommendation/dlrm/quantization/ptq/eager/dlrm_s_pytorch_tune.py
  examples/pytorch/recommendation/dlrm/quantization/ptq/fx/dlrm_s_pytorch_tune.py
  examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/model/torch_model.py
Labels: bug fix, extension test

#332 support multiple path pydocstyle scan
  .azure-pipelines/code-scan.yml
  .azure-pipelines/scripts/codeScan/pydocstyle/pydocstyle.sh
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
Labels: validation

#323 fix yolo_v3 registry bug
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py
Labels: bug fix, extension test

#317 readme and requirement fix
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py
Labels: bug fix, extension test

#346 Enhance model test CI status
  .azure-pipelines/code-scan.yml
  .azure-pipelines/model-test.yml
  .azure-pipelines/scripts/models/collect_log_model.py
  .azure-pipelines/template/model-template.yml
Labels: validation

#344 pruning/log refinement
  neural_compressor/pruner/criteria.py
Labels: documentation

#335 Bench documentation update
  docs/source/_static/imgs/bench/pruning-details.png
  docs/source/_static/imgs/bench/pruning-wizard.png
  docs/source/bench.md
Labels: documentation, review

#312 add export docs
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/_static/imgs/export.png
  docs/source/export.md
Labels: documentation

#331 Improve FX.md
  docs/source/FX.md
Labels: documentation

#281 refined NAS document.
  docs/source/NAS.md
Labels: documentation, review

#339 reformat tensorboard.md to meet new doc requirement
  docs/source/tensorboard.md
Labels: documentation, review

#343 Change the GPT-J example configure setting
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
Labels: examples, extension test

#329 Refined the docs for tuning strategy
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/_static/imgs/Conv2D_PyTorch_Cap.png
  docs/source/sigopt_strategy.md
  docs/source/tuning_strategies.md
  neural_compressor/objective.py
  neural_compressor/ux/web/README.md
Labels: documentation, review

#291 distributed.md doc refine
  docs/source/distributed.md
Labels: documentation, review

#342 Refine the docstring for strategy
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/api-documentation/strategy.rst
  docs/source/api-documentation/strategy/strategy.rst
  neural_compressor/strategy/__init__.py
  neural_compressor/strategy/auto_mixed_precision.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/bayesian.py
  neural_compressor/strategy/conservative.py
  neural_compressor/strategy/exhaustive.py
  neural_compressor/strategy/hawq_v2.py
  neural_compressor/strategy/mse.py
  neural_compressor/strategy/mse_v2.py
  neural_compressor/strategy/random.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/__init__.py
  neural_compressor/strategy/utils/tuning_sampler.py
  neural_compressor/strategy/utils/tuning_space.py
  neural_compressor/strategy/utils/tuning_structs.py
Labels: documentation

#288 Refined CODE_OF_CONDUCT.md and CONTRIBUTING.md
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/CODE_OF_CONDUCT.md
  docs/source/CONTRIBUTING.md
  docs/source/contributions.md
Labels: documentation, review

#352 refine transform.md
  docs/source/transform.md
Labels: documentation

#353 Add doc docstring
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/api-documentation/adaptor.rst
  docs/source/api-documentation/adaptor/onnxrt.rst
  neural_compressor/adaptor/ox_utils/__init__.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/operators/__init__.py
  neural_compressor/adaptor/ox_utils/operators/activation.py
  neural_compressor/adaptor/ox_utils/operators/argmax.py
  neural_compressor/adaptor/ox_utils/operators/attention.py
  neural_compressor/adaptor/ox_utils/operators/binary_op.py
  neural_compressor/adaptor/ox_utils/operators/concat.py
  neural_compressor/adaptor/ox_utils/operators/conv.py
  neural_compressor/adaptor/ox_utils/operators/direct_q8.py
  neural_compressor/adaptor/ox_utils/operators/embed_layernorm.py
  neural_compressor/adaptor/ox_utils/operators/gather.py
  neural_compressor/adaptor/ox_utils/operators/gavgpool.py
  neural_compressor/adaptor/ox_utils/operators/gemm.py
  neural_compressor/adaptor/ox_utils/operators/lstm.py
  neural_compressor/adaptor/ox_utils/operators/matmul.py
  neural_compressor/adaptor/ox_utils/operators/maxpool.py
  neural_compressor/adaptor/ox_utils/operators/ops.py
  neural_compressor/adaptor/ox_utils/operators/pad.py
  neural_compressor/adaptor/ox_utils/operators/pooling.py
  neural_compressor/adaptor/ox_utils/operators/resize.py
  neural_compressor/adaptor/ox_utils/operators/split.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/adaptor/ox_utils/util.py
Labels: documentation

#327 add mxnet utils docstring.
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  neural_compressor/adaptor/mxnet_utils/util.py
Labels: documentation

#349 add docstring
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  neural_compressor/algorithm/__init__.py
  neural_compressor/algorithm/algorithm.py
  neural_compressor/algorithm/fast_bias_correction.py
  neural_compressor/algorithm/weight_correction.py
Labels: documentation

#318 Update model docstring
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/api-documentation/apis.rst
  docs/source/api-documentation/model.rst
  neural_compressor/model/__init__.py
  neural_compressor/model/base_model.py
  neural_compressor/model/keras_model.py
  neural_compressor/model/model.py
  neural_compressor/model/mxnet_model.py
  neural_compressor/model/nets_factory.py
  neural_compressor/model/onnx_model.py
  neural_compressor/model/tensorflow_model.py
  neural_compressor/model/torch_model.py
Labels: documentation

#324 Doc refine
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/dataloader.md
  docs/source/dataset.md
Labels: documentation

#330 Docs refine with release info, legal info, installation guide
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  docs/source/installation_guide.md
  docs/source/legal_information.md
  docs/source/releases_info.md
  third-party-programs.txt
Labels: documentation, review

#307 Refined docstring for API of pruners.
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  neural_compressor/pruner/pruner_legacy/__init__.py
  neural_compressor/pruner/pruner_legacy/gradient_sensitivity.py
  neural_compressor/pruner/pruner_legacy/group_lasso.py
  neural_compressor/pruner/pruner_legacy/magnitude.py
  neural_compressor/pruner/pruner_legacy/pattern_lock.py
  neural_compressor/pruner/pruner_legacy/pruner.py
  neural_compressor/pruner/pruner_legacy/util/block_mask.py
Labels: documentation

#336 Docs refine with benchmark and validate data
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/benchmark.md
  docs/source/platform_configuration.md
  docs/source/validated_model_list.md
  examples/helloworld/README.md
  examples/helloworld/tf_example7/README.md
  neural_compressor/benchmark.py
  neural_compressor/experimental/benchmark.py
Labels: documentation, review

#360 Merge backend_quant.md content to quantization.md
  docs/source/PTQ.md
  docs/source/QAT.md
  docs/source/backend_quant.md
  docs/source/dynamic_quantization.md
  docs/source/quantization.md
Labels: documentation

#333 Add Auto API for utils
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/api-documentation/apis.rst
  docs/source/api-documentation/utils.rst
  neural_compressor/utils/__init__.py
  neural_compressor/utils/collect_layer_histogram.py
  neural_compressor/utils/constant.py
  neural_compressor/utils/create_obj_from_config.py
  neural_compressor/utils/kl_divergence.py
  neural_compressor/utils/load_huggingface.py
  neural_compressor/utils/logger.py
  neural_compressor/utils/options.py
  neural_compressor/utils/pytorch.py
  neural_compressor/utils/utility.py
Labels: documentation

#347 Refine docstring for newAPI, algorithm, and contrib
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/api-documentation/algorithm.rst
  docs/source/api-documentation/apis.rst
  docs/source/api-documentation/contrib.rst
  docs/source/api-documentation/newAPI.rst
  docs/source/api-documentation/newAPI/benchmark.rst
  docs/source/api-documentation/newAPI/objective.rst
  docs/source/api-documentation/newAPI/quantization.rst
  docs/source/api-documentation/newAPI/training.rst
  neural_compressor/benchmark.py
  neural_compressor/contrib/__init__.py
  neural_compressor/contrib/strategy/__init__.py
  neural_compressor/contrib/strategy/sigopt.py
  neural_compressor/contrib/strategy/tpe.py
  neural_compressor/objective.py
  neural_compressor/quantization.py
  neural_compressor/training.py
Labels: documentation

#379 update publications
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  docs/source/publication_list.md
Labels: documentation

#372 fix numpy version for old_api_example
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/eager/nnUnet/requirements.txt
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/requirements.txt
Labels: bug fix

#228 Modify NAS n_worker as a variable
  neural_compressor/conf/config.py
  neural_compressor/experimental/nas/dynas.py
  neural_compressor/experimental/nas/dynast/dynas_utils.py
Labels: enhancement, review

#356 fix dlrm and asr benchmark
  examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py
  examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/run_benchmark.sh
  examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/run_asr.py
Labels: bug fix

#341 Turn off BF16 conversion for some models whose accuracy can't reach the goal
  examples/tensorflow/image_recognition/tensorflow_models/quantization/ptq/inception_v3.yaml
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/bert.yaml
  examples/tensorflow/object_detection/tensorflow_models/quantization/ptq/faster_rcnn_inception_resnet_v2.yaml
  examples/tensorflow/object_detection/tensorflow_models/quantization/ptq/faster_rcnn_resnet101.yaml
Labels: bug fix

#366 Fix OOB wide_deep tuning failed issue
  examples/tensorflow/oob_models/quantization/ptq/README.md
  examples/tensorflow/oob_models/quantization/ptq/tf_benchmark.py
Labels: bug fix

#381 Update PyTorch text-classification examples with new API
  examples/.config/model_params_pytorch.json
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/conf.yaml
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/conf.yaml
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/conf_qat.yaml
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py
Labels: examples, extension test

#380 Fix efficientnet_b0 tuning failed with Op type not registered swish_f32
  neural_compressor/adaptor/tf_utils/graph_converter.py
Labels: bug fix

#359 Refine docs with new API samples
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/distillation.md
  docs/source/mixed_precision.md
  docs/source/model.md
  docs/source/objective.md
  docs/source/orchestration.md
  docs/source/pruning.md
  docs/source/quantization.md
Labels: documentation

#304 add doc strings
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/api-documentation/adaptor.rst
  docs/source/api-documentation/adaptor/torch_utils.rst
  docs/source/api-documentation/adaptor/torch_utils/bf16_convert.rst
  docs/source/api-documentation/adaptor/torch_utils/hawq_metric.rst
  docs/source/api-documentation/adaptor/torch_utils/onnx.rst
  docs/source/api-documentation/adaptor/torch_utils/symbolic_trace.rst
  docs/source/api-documentation/adaptor/torch_utils/util.rst
  docs/source/api-documentation/component/ModelConversion.rst
  docs/source/api-documentation/new_api.rst
  docs/source/api-documentation/new_api/config.rst
  docs/source/api-documentation/new_api/mix_precision.rst
  neural_compressor/__init__.py
  neural_compressor/adaptor/torch_utils/__init__.py
  neural_compressor/adaptor/torch_utils/bf16_convert.py
  neural_compressor/adaptor/torch_utils/hawq_metric.py
  neural_compressor/adaptor/torch_utils/onnx.py
  neural_compressor/adaptor/torch_utils/symbolic_trace.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/config.py
  neural_compressor/mix_precision.py
  neural_compressor/pruner/pruners.py
  neural_compressor/version.py
Labels: documentation, review

#383 Fix typo in graph_converter.py
  neural_compressor/adaptor/tf_utils/graph_converter.py
Labels: documentation

#390 Fix CI mxnet issue
  .azure-pipelines/scripts/models/env_setup.sh
  .azure-pipelines/scripts/models/run_mxnet_models_trigger.sh
  neural_compressor/experimental/benchmark.py
Labels: bug fix

#364 Add quantization example of stable diffusion model
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/README.md
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/base_images/image.jpg
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/ptq_static/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-to-image/quantization/run_diffusion.py
Labels: examples, extension test

#348 update pruning doc_details
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/pruning_details.md
  docs/source/validated_model_list.md
  examples/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/run_glue_no_trainer.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/run_glue_no_trainer_mixed.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/bert-mini/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/distillation_config.yaml
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/pruning_config.yaml
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/run_glue_no_trainer_sparse.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/legacy/pruning_while_distillation/group_lasso/eager/run_glue_prune_distillation.sh
  neural_compressor/pruner/README.md
Labels: documentation

#351 fix gradient based criterion bug
  neural_compressor/experimental/pruning_v2.py
  neural_compressor/pruner/criteria.py
  neural_compressor/pruner/pruners.py
Labels: bug fix, review

#369 Fix OOB centernet_hg104 benchmark issue
  examples/tensorflow/oob_models/quantization/ptq/model_detail.py
  examples/tensorflow/oob_models/quantization/ptq/tf_benchmark.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
Labels: bug fix
