Repository intel/neural-compressor, pull requests merged in 2023-02, with the labels that each got.

#431 Enable ORT hf stage1 static quantization example
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq/trainer_qa.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/export.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/trainer_qa.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/utils_model.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/utils_qa.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/export.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/trainer_qa.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/utils_model.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/utils_qa.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/export.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/prepare_data.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/export.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/prepare_data.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/run_tuning.sh
Labels: examples

#432 Doc revision for the newapi example
  examples/pytorch/nlp/huggingface_models/text-classification/distillation/eager/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/distillation_for_quantization/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/prune_once_for_all/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/README.md
Labels: documentation

#481 No need to be logged in for model download
  examples/pytorch/diffusion_model/diffusers/textual_inversion/README.md
Labels: documentation

#475 add yolo_v3 to 2.0
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/LICENSE
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/README.md
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/YOLOV3_README.md
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/config/coco.data
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/config/create_custom_model.sh
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/config/custom.data
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/config/yolov3-tiny.cfg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/config/yolov3.cfg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/coco.names
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/custom/classes.names
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/custom/images/train.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/custom/labels/train.txt
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/custom/train.txt
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/custom/valid.txt
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/get_coco_dataset.sh
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/dog.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/eagle.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/field.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/giraffe.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/herd_of_horses.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/messi.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/person.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/room.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/data/samples/street.jpg
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/detect.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/models.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/requirements.txt
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/test.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/train.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/__init__.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/augmentations.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/datasets.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/logger.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/parse_config.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/utils/utils.py
  examples/pytorch/object_detection/yolo_v3/quantization/ptq_static/fx/weights/download_weights.sh
Labels: examples, extension test

#531 Fix dlrm fx example
  examples/pytorch/recommendation/dlrm/quantization/ptq/fx/dlrm_s_pytorch_tune.py
Labels: bug fix

#461 Supported multi-nodes for QAT on ResNet.
  examples/pytorch/diffusion_model/diffusers/textual_inversion/distillation_for_quantization/README.md
  examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/README.md
  examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/requirements.txt
Labels: examples

#536 add new models in windows
  examples/.config/model_params_onnxrt_win.json
  examples/.config/model_params_pytorch_win.json
  examples/.config/model_params_tensorflow_win.json
  examples/onnxrt/object_detection/onnx_model_zoo/DUC/quantization/ptq/main.py
Labels: validation

#469 Enable tensorflow NLP examples using new API
  examples/.config/model_params_tensorflow.json
  examples/README.md
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/README.md
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/create_pretraining_data.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/create_tf_record.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/evaluate_squad.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/export_classifier.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/freeze_estimator_to_pb.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/generic_ops.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/modeling.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/optimization.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/prepare_dataset.sh
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/prepare_model.sh
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/run_benchmark.sh
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/run_tuning.sh
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/tokenization.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/tune_squad.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/README.md
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/create_pretraining_data.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/create_tf_record.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/evaluate_squad.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/export_classifier.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/freeze_estimator_to_pb.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/generic_ops.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/modeling.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/optimization.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/prepare_dataset.sh
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/prepare_model.sh
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/run_benchmark.sh
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/run_tuning.sh
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/tokenization.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/tune_squad.py
  neural_compressor/data/__init__.py
  neural_compressor/data/transforms/__init__.py
  neural_compressor/metric/__init__.py
Labels: examples, extension test

#544 Added distributed training support for distillation of Resnet50.
  examples/pytorch/image_recognition/torchvision_models/distillation/eager/README.md
  examples/pytorch/image_recognition/torchvision_models/distillation/eager/main.py
  examples/pytorch/image_recognition/torchvision_models/distillation/eager/requirements.txt
Labels: examples

#533 add UT for logger
  test/utils/test_logger.py
Labels: extension test

#543 main readme description update
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  docs/source/publication_list.md
Labels: documentation

#528 Support Pruning new API for TF backend
  examples/README.md
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/README.md
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/main.py
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/prepare_model.py
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/requirements.txt
  examples/tensorflow/image_recognition/inception_v3/imagenet_prepare/build_imagenet_data.py
  examples/tensorflow/image_recognition/inception_v3/imagenet_prepare/download_and_convert_imagenet.sh
  examples/tensorflow/image_recognition/inception_v3/imagenet_prepare/download_imagenet.sh
  examples/tensorflow/image_recognition/inception_v3/imagenet_prepare/imagenet_lsvrc_2015_synsets.txt
  examples/tensorflow/image_recognition/inception_v3/imagenet_prepare/imagenet_metadata.txt
  examples/tensorflow/image_recognition/inception_v3/prepare_dataset.sh
  examples/tensorflow/image_recognition/inception_v3/pruning/magnitude/README.md
  examples/tensorflow/image_recognition/inception_v3/pruning/magnitude/main.py
  examples/tensorflow/image_recognition/inception_v3/pruning/magnitude/requirements.txt
  examples/tensorflow/image_recognition/resnet_v2/pruning/magnitude/README.md
  examples/tensorflow/image_recognition/resnet_v2/pruning/magnitude/main.py
  neural_compressor/experimental/pruning_v2.py
  neural_compressor/pruner/pruner_legacy/pruner.py
  neural_compressor/pruner/utils.py
Labels: review

#540 Removed the fake evaluation function
  .azure-pipelines/scripts/models/collect_log_model.py
  .azure-pipelines/scripts/models/generate_report.sh
  neural_compressor/contrib/strategy/sigopt.py
  neural_compressor/experimental/quantization.py
  neural_compressor/strategy/auto_mixed_precision.py
  neural_compressor/strategy/conservative.py
  neural_compressor/strategy/strategy.py
  test/config/test_pythonic_config.py
  test/strategy/test_basic.py
Labels: enhancement

#564 PyTorch/IPEX framework yaml refactoring
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/pytorch_cpu.yaml
  neural_compressor/adaptor/pytorch_ipex.yaml
Labels: review

#470 Enable INC Distributed Tuning
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_distributed_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py
  neural_compressor/conf/config.py
  neural_compressor/conf/pythonic_config.py
  neural_compressor/config.py
  neural_compressor/experimental/quantization.py
  neural_compressor/objective.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/strategy.py
  test/strategy/test_distributed_tuning.py
Labels: new feature

#532 Optimize Windows multi-instance benchmark
  neural_compressor/experimental/benchmark.py
Labels: extension test

#430 Fixed bug when regularization is applied and zero elements overflows.
  neural_compressor/pruner/patterns.py
  test/pruning/test_pruning_regs.py
Labels: review

#575 fix force stop workspace clean issue
  .azure-pipelines/template/docker-template.yml
  neural_compressor/__init__.py
Labels: validation

#571 add default value for recipes
  neural_compressor/config.py
  neural_compressor/strategy/strategy.py
  test/config/test_config.py
Labels: bug fix

#554 Enable onnx model quantization with trt ep
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/util.py
Labels: enhancement, review, extension test

#273 Support FP16/BF16 for onnxrt adaptor
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/mixed_precision.md
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/onnxrt_cuda.yaml
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/operators/direct_q8.py
  neural_compressor/adaptor/ox_utils/operators/ops.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/conf/config.py
  neural_compressor/conf/pythonic_config.py
  neural_compressor/config.py
  neural_compressor/contrib/strategy/sigopt.py
  neural_compressor/contrib/strategy/tpe.py
  neural_compressor/data/datasets/dataset.py
  neural_compressor/data/filters/filter.py
  neural_compressor/data/transforms/transform.py
  neural_compressor/experimental/data/dataloaders/dataloader.py
  neural_compressor/experimental/data/datasets/dataset.py
  neural_compressor/experimental/data/filters/filter.py
  neural_compressor/experimental/data/transforms/transform.py
  neural_compressor/experimental/metric/metric.py
  neural_compressor/experimental/mixed_precision.py
  neural_compressor/metric/metric.py
  neural_compressor/mix_precision.py
  neural_compressor/strategy/auto_mixed_precision.py
  neural_compressor/utils/utility.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
  test/mixed_precision/test_mixed_precision.py
  test/quantization/test_quantization.py
Labels: new feature

#570 Tuning recipe
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/algorithm/algorithm.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/conservative.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/constant.py
  neural_compressor/strategy/utils/tuning_sampler.py
  neural_compressor/strategy/utils/tuning_space.py
  neural_compressor/strategy/utils/utility.py
  neural_compressor/utils/constant.py
  neural_compressor/utils/create_obj_from_config.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: review, new feature

#572 migrate NLP examples
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/run_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_tuning.sh
Labels: examples, extension test

#565 Fix ORT domain detection failure for large model
  neural_compressor/adaptor/onnxrt.py
Labels: bug fix, review

#584 Fix onnxrt adaptor
  neural_compressor/adaptor/onnxrt.py
Labels: bug fix

#590 Adjust O0 and only attempt to quantize conv and matmul
  neural_compressor/strategy/conservative.py
Labels: enhancement, review

#585 support non traceable module in fine-grained FX
  neural_compressor/adaptor/pytorch.py
Labels: enhancement

#589 Refine ORT QDQ quantization graph
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/experimental/benchmark.py
  neural_compressor/model/onnx_model.py
  test/model/test_onnx_model.py
Labels: enhancement, review, extension test
