Repository intel/neural-compressor, pull requests merged in 2023-12, with the labels that each got.

#1432 Add clip for onnxrt smoothquant
  neural_compressor/adaptor/ox_utils/smooth_quant.py
  test/algorithm/test_smooth_quant_onnx.py
Labels: bug fix

#1429 fix coverity issue
  docker/Dockerfile
  docker/Dockerfile.devel
  examples/onnxrt/nlp/onnx_model_zoo/bert-squad/quantization/ptq_dynamic/run_onnx_squad.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py
  examples/pytorch/object_detection/ssd_resnet34/quantization/qat/fx/ssd/utils.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/rnn.py
  examples/tensorflow/nlp/transformer_lt_mlperf/quantization/ptq/mlperf_compliance/tf_mlperf_log.py
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py
  neural_compressor/adaptor/ox_utils/operators/split.py
  neural_compressor/adaptor/ox_utils/weight_only.py
  neural_compressor/adaptor/tf_utils/quantize_graph/qdq/fuse_qdq_conv.py
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  test/strategy/test_sigopt_1.x.py
Labels: enhancement

#1442 check ipex version instead of torch version
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#1431 change use_optimum_format=True and add bias
  docs/source/quantization_weight_only.md
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/model/torch_model.py
  neural_compressor/torch/quantization/modules.py
  neural_compressor/utils/load_huggingface.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/model/test_model_pytorch.py
Labels: bug fix

#1350 add llm evaluate for language modeling
  README.md
  docs/source/smooth_quant.md
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/cnn_dm_dataset.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run-gptq-llm.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_gptj_mlperf_int4.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_gptj_mlperf_int4.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_quant.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/benchmark.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/run_quant.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/hf_eval/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/hf_eval/datasets/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/hf_eval/datasets/cnn_dailymail.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/hf_eval/evaluator.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/hf_eval/hf_datasets/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/hf_eval/hf_datasets/cnn_dailymail.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_code_eval/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_code_eval/evaluator.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/evaluator.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/models/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/models/huggingface.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/tasks/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/tasks/lambada.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_clm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_quant.sh
Labels: examples

#1434 Add layer wise quantization doc and ONNXRT example
  README.md
  docs/source/imgs/lwq_ort.png
  docs/source/quantization_layer_wise.md
  docs/source/quantization_weight_only.md
  docs/source/user_guide.md
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/model/onnx_model.py
Labels: documentation, examples

#1438 Fix bugs in ONNXRT examples for v2.4
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/image_recognition/unet/quantization/ptq_static/README.md
  examples/onnxrt/image_recognition/unet/quantization/ptq_static/main.py
  examples/onnxrt/image_recognition/unet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/prepare_model.py
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/prepare_model.py
  examples/onnxrt/nlp/roberta/quantization/ptq_static/prepare_model.py
  neural_compressor/adaptor/ox_utils/operators/lstm.py
Labels: bug fix

#940 Remove Dequantize Cast Optimizer MIN_FIRST limitation for spr-base
  neural_compressor/adaptor/tf_utils/graph_rewriter/bf16/dequantize_cast_optimizer.py
  test/tfnewapi/test_tensorflow_graph_dequantize_cast_optimizer_newapi.py
Labels: bug fix

#1448 Update ONNXRT layoutlmv2 example README
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/README.md
Labels: bug fix

#1447 Add bias for fx_model
  neural_compressor/adaptor/torch_utils/util.py
Labels: bug fix

#1451 fix pt notebook benchmark
  examples/notebook/pytorch/Quick_Started_Notebook_of_INC_for_Pytorch.ipynb
  examples/notebook/pytorch/benchmark.py
Labels: bug fix

#1454 Enhance ONNXRT log info
  neural_compressor/adaptor/onnxrt.py
Labels: bug fix

#1459 Update model link from ONNX model zoo
  examples/onnxrt/body_analysis/onnx_model_zoo/arcface/quantization/ptq_static/prepare_model.py
  examples/onnxrt/body_analysis/onnx_model_zoo/emotion_ferplus/quantization/ptq_static/prepare_model.py
  examples/onnxrt/body_analysis/onnx_model_zoo/ultraface/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/alexnet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/caffenet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/densenet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/efficientnet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/fcn/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/googlenet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/inception/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/mnist/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/mobilenet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/resnet50/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/squeezenet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/vgg16/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/onnx_model_zoo/zfnet/quantization/ptq_static/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlm/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlm/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/main.py
  examples/onnxrt/nlp/onnx_model_zoo/BiDAF/quantization/ptq_dynamic/prepare_model.py
  examples/onnxrt/nlp/onnx_model_zoo/bert-squad/quantization/ptq_dynamic/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/DUC/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/mask_rcnn/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/ssd/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/tiny_yolov3/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/yolov3/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq_static/prepare_model.py
Labels: bug fix

#1460 Remove Version Check for tf.estimator
  neural_compressor/model/tensorflow_model.py
Labels: bug fix

#1457 Update GPTQ example's documentation
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run-gptq-llm.sh
Labels: documentation

#1455 Update example scripts for ONNXRT DML EP verify
  examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/main.py
  examples/onnxrt/image_recognition/onnx_model_zoo/vgg16/quantization/ptq_static/main.py
  examples/onnxrt/image_recognition/resnet50_torchvision/quantization/ptq_static/main.py
  examples/onnxrt/nlp/bert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/main.py
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/benchmark.py
Labels: examples

#1473 Fixed inputs error for smoothquant example_inputs
  neural_compressor/adaptor/torch_utils/smooth_quant.py
Labels: bug fix

#1414 [WOQ]support AutoRound
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/eval.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/main.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/parse_results.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/autoround/utils.py
  neural_compressor/adaptor/torch_utils/autoround/__init__.py
  neural_compressor/adaptor/torch_utils/autoround/autoround.py
  neural_compressor/adaptor/torch_utils/autoround/sign_sgd.py
  test/algorithm/test_autoround.py
Labels: new feature

#1462 Update framework versions for CI
  .azure-pipelines/model-test.yml
  .azure-pipelines/scripts/fwk_version.sh
  .azure-pipelines/scripts/models/run_mxnet_models_trigger.sh
  .azure-pipelines/scripts/models/run_onnxrt_models_trigger.sh
  .azure-pipelines/scripts/models/run_pytorch_models_trigger.sh
  .azure-pipelines/scripts/models/run_tensorflow_models_trigger.sh
  .azure-pipelines/scripts/ut/env_setup.sh
  .azure-pipelines/scripts/ut/run_basic_adaptor.sh
  .azure-pipelines/scripts/ut/run_basic_adaptor_tfnewapi.sh
  .azure-pipelines/scripts/ut/run_basic_api.sh
  .azure-pipelines/scripts/ut/run_basic_itex.sh
  .azure-pipelines/scripts/ut/run_basic_others.sh
  .azure-pipelines/scripts/ut/run_basic_pt_pruning.sh
  .azure-pipelines/scripts/ut/run_basic_tf_pruning.sh
  .azure-pipelines/scripts/ut/run_basic_v2.1_ipex.sh
  .azure-pipelines/scripts/ut/run_itrex.sh
  .azure-pipelines/scripts/ut/ut_fwk_version.sh
  .azure-pipelines/template/docker-template.yml
  .azure-pipelines/template/model-template.yml
  .azure-pipelines/template/ut-template.yml
  .azure-pipelines/ut-3x-pt.yml
  .azure-pipelines/ut-3x-tf.yml
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
  neural_compressor/utils/pytorch.py
  test/data/test_dataloader.py
  test/distributed/test_distributed_metrics.py
  test/distributed/test_distributed_pt_train.py
  test/model/test_model_pytorch.py
Labels: validation

#1480 Update example notebooks for search with DyNAS-T
  examples/notebook/dynas/BERT_SST2_Supernet_NAS.ipynb
  examples/notebook/dynas/MobileNetV3_Supernet_Distributed_NAS.ipynb
  examples/notebook/dynas/MobileNetV3_Supernet_NAS.ipynb
  examples/notebook/dynas/ResNet50_Quantiation_Search_Supernet_NAS.ipynb
Labels: bug fix

#1456 [bug fix] update quantizable add ops detection on IPEX backend
  neural_compressor/adaptor/torch_utils/util.py
  test/ipex/test_adaptor_ipex.py
Labels: bug fix

#1499 Fix llm model accuracy regression with IPEX 2.1.100
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#1439 Fix bug with range step in ORTSmoothQuant._auto_tune_alpha()
  neural_compressor/adaptor/ox_utils/smooth_quant.py
Labels: bug fix

#1475 add code-generaion evaluation for woq gptq
  examples/.config/model_params_pytorch.json
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_quant.sh
Labels: examples
