Repository intel/neural-compressor, pull requests merged in 2023-09, with the labels that each got.

#1203 Support all calibration samples for ONNXRT weight only
  neural_compressor/adaptor/ox_utils/weight_only.py
Labels: enhancement

#1207 Remove Version Limits for tf2oonx Examples
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
Labels: bug fix

#1211 fix pruning
  neural_compressor/compression/pruner/criteria.py
  neural_compressor/compression/pruner/patterns/base.py
  neural_compressor/compression/pruner/patterns/ninm.py
  neural_compressor/compression/pruner/patterns/nxm.py
  neural_compressor/compression/pruner/pruners/progressive.py
Labels: bug fix

#1215 support abode analytics
  README.md
  docs/build_docs/build.sh
  docs/build_docs/source/_templates/footer.html
  docs/build_docs/source/_templates/layout.html
  docs/build_docs/source/conf.py
Labels: enhancement

#1214 fix bug when trace failed
  neural_compressor/adaptor/pytorch_cpu.yaml
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix

#1195 add tf resnet quantization notebook
  examples/README.md
  examples/notebook/tensorflow/resnet/README.md
  examples/notebook/tensorflow/resnet/resnet_benchmark.py
  examples/notebook/tensorflow/resnet/resnet_quantization.ipynb
Labels: examples

#1219 Fix pytorch dataloader batchsize issue
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#1205 refine readme
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_sparsegpt.py
Labels: examples

#1223 add validated WOQ results
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/quantization_weight_only.md
  docs/source/validated_model_list.md
Labels: documentation

#1210 Update DyNAS-T to 1.5
  .azure-pipelines/scripts/ut/env_setup.sh
  examples/notebook/dynas/ResNet50_Quantiation_Search_Supernet_NAS.ipynb
  neural_compressor/conf/config.py
  neural_compressor/experimental/nas/dynas.py
  test/nas/test_nas.py
  test/requirements.txt
Labels: enhancement

#1224 fix pruning kthvalue error
  neural_compressor/compression/pruner/patterns/base.py
  neural_compressor/compression/pruner/patterns/ninm.py
  neural_compressor/compression/pruner/patterns/nxm.py
Labels: bug fix

#1075 migrate maskrcnn to API 2.x
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/README.md
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/download_dataset.sh
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/download_weights.sh
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/LICENSE
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/TROUBLESHOOTING.md
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/configs/e2e_mask_rcnn_R_50_FPN_1x.yaml
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/maskrnn.patch
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/setup.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/tools/cityscapes/convert_cityscapes_to_coco.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/tools/cityscapes/instances2dict_with_polygons.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/tools/test_net.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/tools/train_mlperf.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/pytorch/tools/train_net.py
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/requirements.txt
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/run_and_time.sh
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/run_benchmark.sh
  examples/pytorch/object_detection/maskrcnn/quantization/ptq/fx/run_quant.sh
Labels: examples

#1218 fix device issue of sq
  examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/run_asr.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix

#1222 Fix bert_base_mrpc smoothquant check_shape issue
  neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py
Labels: bug fix

#1212 Unify GPTQ dataloader with fixed/unfixed length data
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/gptq.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test_weight_only_quantization.py
Labels: enhancement

#1043 Add table transformer example
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/export.sh
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/patch
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/prepare.sh
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/requirements.txt
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/run_tuning.sh
Labels: examples

#1240 add oneCICD golden pipeline for code scan
  .github/workflows/Scanner_Bdba.yml
  .github/workflows/Scanner_Coverity.yml
  .github/workflows/Scanner_McAfee.yml
Labels: validation

#1242 Enhance export related UT
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/main.py
  neural_compressor/experimental/export/torch2onnx.py
  neural_compressor/model/torch_model.py
  test/algorithm/test_algorithm.py
  test/export/test_onnx_qlieanr_to_qdq.py
  test/export/test_torch2onnx.py
Labels: enhancement

#1243 Fix get_model_path output for TF models
  neural_compressor/utils/neural_insights_utils.py
  setup.py
Labels: bug fix

#1235 Enhance weight-only for onnxrt backend
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/weight_only.py
  neural_compressor/model/onnx_model.py
  test/adaptor/onnxrt_adaptor/test_weight_only_adaptor.py
Labels: enhancement, WIP

#1237 Enhance Unit Test of pruning with pt
  test/pruning_with_pt/pruning_1.x_v1/test_pruning_gradient_sensitivity.py
  test/pruning_with_pt/pruning_1.x_v1/test_pruning_group_lasso.py
  test/pruning_with_pt/pruning_1.x_v1/test_pruning_pattern_lock.py
  test/pruning_with_pt/pruning_1.x_v1/test_pruning_pure_yaml.py
  test/pruning_with_pt/pruning_1.x_v2/test_pruning_regs.py
Labels: WIP

#1254 Fix BF16 Output for TF GraphSage Example
  examples/tensorflow/graph_networks/graphsage/quantization/ptq/main.py
Labels: bug fix

#1258 Update readme for v2.3 release
  README.md
  docs/source/imgs/wechat_group.jpg
  docs/source/installation_guide.md
  docs/source/publication_list.md
  docs/source/quantization.md
  third-party-programs.txt
Labels: documentation

#1097 migrate rnnt to API 2.x
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/QSL.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/accuracy_eval.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/mlperf.conf
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/prepare_dataset.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/prepare_loadgen.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/Dockerfile
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/LICENSE
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/configs/rnnt.toml
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/dataset.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/decoders.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/helpers.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/metrics.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/model_separable_rnnt.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/features.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/manifest.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/segment.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/text/LICENSE
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/text/__init__.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/text/cleaners.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/parts/text/numbers.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/preprocessing.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/rnn.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/docker/build.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/docker/launch.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/download_librispeech.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/evaluation.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/inference.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/inference_benchmark.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/preprocess_librispeech.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/train.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/scripts/train_benchmark.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/utils/__init__.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/utils/convert_librispeech.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/utils/download_librispeech.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/utils/download_utils.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch/utils/preprocessing_utils.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/pytorch_SUT.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/requirements.txt
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/run.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/run_quant.sh
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/run_tune.py
  examples/pytorch/speech_recognition/rnnt/quantization/ptq_dynamic/fx/user.conf
Labels: examples

#1271 downgrade onnxruntime-extensions version
  .azure-pipelines/scripts/ut/env_setup.sh
Labels: validation

#1266 Reduce memory consumption in ONNXRT adaptor
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/model/onnx_model.py
  test/model/test_onnx_model.py
Labels: enhancement
