Repository intel/neural-compressor, pull requests merged in 2023-01, with the labels that each got.

#449 improve logging of scale and zero_point during fx static quantization
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#355 ITEX quantization run on the device user specified
  neural_compressor/experimental/benchmark.py
  neural_compressor/experimental/component.py
  neural_compressor/model/tensorflow_model.py
Labels: extension test

#463 mark 1.x API examples with flag
  examples/README.md
Labels: documentation

#456 improve ipex example benchmark
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/main.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
  examples/pytorch/object_detection/ssd_resnet34/quantization/ptq/ipex/infer.py
  examples/pytorch/recommendation/dlrm/quantization/ptq/ipex/dlrm_s_pytorch.py
  neural_compressor/utils/pytorch.py
Labels: extension test

#426 Refine TF Object Detection Examples For New API
  examples/.config/model_params_tensorflow.json
  examples/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/tensorflow_models/mask_rcnn_inception_v2/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/mask_rcnn_inception_v2/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/mask_rcnn_inception_v2/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/mask_rcnn_inception_v2/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/tensorflow_models/prepare_dataset.sh
  examples/tensorflow/object_detection/tensorflow_models/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/prepare_model.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/label_map.yaml
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/prepare_model.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/README.md
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/coco_constants.py
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/prepare_dataset.sh
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/requirements.txt
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/run_benchmark.sh
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/run_tuning.sh
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/utils.py
  neural_compressor/data/__init__.py
  neural_compressor/data/datasets/__init__.py
  neural_compressor/data/filters/__init__.py
  neural_compressor/data/transforms/__init__.py
  neural_compressor/metric/__init__.py
  neural_compressor/model/tensorflow_model.py
Labels: examples, extension test
