Repository intel/neural-compressor, pull requests merged in 2023-08, with the labels that each got.

#1104 GPTQ feature enhance
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/datautils.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/evaluator.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/models/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/models/huggingface.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/tasks/__init__.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/evaluation/lm_eval/tasks/lambada.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.sh
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/gptq.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/model/torch_model.py
  neural_compressor/strategy/strategy.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test_weight_only_quantization.py
Labels: enhancement

#1125 fix example dataloader for transformers 4.31.x
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_clm.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/run_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
  examples/pytorch/nlp/huggingface_models/summarization/quantization/ptq_dynamic/fx/run_summarization.py
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/run_glue.py
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_translation.py
Labels: bug fix, extension test

#1115 Fix bug in ONNXRT adapter where _rename_node function fails with model size > 2 GB
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: bug fix

#1123 Enhance ONNX SmoothQuant tuning structure
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/smooth_quant.py
  neural_compressor/config.py
  neural_compressor/model/onnx_model.py
  test/algorithm/test_smooth_quant_onnx.py
Labels: enhancement

#985 Add LLaMa onnx example
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  .azure-pipelines/scripts/codeScan/pyspelling/pyspelling_conf.yaml
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_dynamic/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/gptj/quantization/ptq_static/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/prompt.json
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/run_quant.sh
  neural_compressor/model/onnx_model.py
  test/model/test_onnx_model.py
  test/requirements.txt
Labels: examples, extension test

#1133 Fix precision tuning bug for ONNX CUDA EP
  neural_compressor/strategy/utils/constant.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: bug fix

#1131 Fix Regression of TF2ONNX Examples
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
Labels: bug fix

#1129 fix PT gpt-j-6B_sq/bloom-560m_sq failed with SQ
  neural_compressor/adaptor/torch_utils/smooth_quant.py
Labels: bug fix

#1124 Refine Docs for TF Image Recognition Models
  examples/tensorflow/image_recognition/resnet_v2/quantization/qat/README.md
  examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_resnet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v4/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v3/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/mixed_precision/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_152/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_50/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vgg19/quantization/ptq/README.md
Labels: documentation

#1091 Add GPTQ-GPTJ examples
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/cnn_dm_dataset.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_gptj_mlperf_int4.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_gptj_mlperf_int4.sh
Labels: examples

#1126 Update Check for ITEX installation
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  neural_compressor/adaptor/keras.py
  neural_compressor/adaptor/tensorflow.py
  test/itex/test_tensorflow_itex_basic.py
  test/tfnewapi/test_tensorflow_itex_qdq.py
Labels: enhancement

#994 layer-wise quant
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/__init__.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/modified_pickle.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/quantize.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/torch_load.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/utils.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/compression/pruner/pruners/progressive.py
  neural_compressor/config.py
  neural_compressor/strategy/strategy.py
  neural_compressor/utils/constant.py
  test/algorithm/test_layer_wise_quant.py
  test/requirements.txt
Labels: new feature

#1055 Support weight only for ONNX
  docs/source/quantization_weight_only.md
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/onnxrt.yaml
  neural_compressor/adaptor/ox_utils/weight_only.py
  neural_compressor/model/onnx_model.py
  neural_compressor/strategy/strategy.py
  test/adaptor/onnxrt_adaptor/test_weight_only_adaptor.py
  test/requirements.txt
Labels: new feature

#1103 Neural Insights: step by step debug example docs
  docs/source/diagnosis.md
  neural_insights/README.md
  neural_insights/docs/source/imgs/accuracy_decrease.png
  neural_insights/docs/source/imgs/activations_summary.png
  neural_insights/docs/source/imgs/activations_summary_onnx.jpg
  neural_insights/docs/source/imgs/min-max.jpg
  neural_insights/docs/source/imgs/ops_weights.png
  neural_insights/docs/source/imgs/tune_result.png
  neural_insights/docs/source/imgs/tune_result2.png
  neural_insights/docs/source/imgs/weights_histogram.png
  neural_insights/docs/source/imgs/weights_histograms.png
  neural_insights/docs/source/imgs/weights_summary_onnx.jpg
  neural_insights/docs/source/onnx_accuracy_debug.md
  neural_insights/docs/source/tf_accuracy_debug.md
Labels: documentation

#1141 fix conda dependencies
  conda_meta/neural_insights/meta.yaml
  conda_meta/neural_solution/meta.yaml
Labels: bug fix

#1121 Add CodeBert ONNX model
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/prepare_data.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/run_fine_tuning.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_dynamic/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/prepare_data.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/run_fine_tuning.sh
  examples/onnxrt/nlp/huggingface_model/code_detection/quantization/ptq_static/run_quant.sh
Labels: examples

#1065 create a new branch for auto-tuning pr
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
Labels: enhancement

#1132 GPTQ evaluation on CPU
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
Labels: bug fix

#1130 Refactor AWQ algo to enhance memory, computation and support foldng=False
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/quantization_weight_only.md
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/awq.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/adaptor/torch_utils/teq.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/model/torch_model.py
  neural_compressor/utils/pytorch.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test.py
  test/quantization/test_weight_only_quantization.py
Labels: enhancement

#1151 Support more ONNX direct INT8 ops
  neural_compressor/adaptor/onnxrt.yaml
  neural_compressor/adaptor/onnxrt_cuda.yaml
  neural_compressor/adaptor/ox_utils/operators/binary_op.py
  neural_compressor/adaptor/ox_utils/operators/direct_q8.py
  neural_compressor/adaptor/ox_utils/operators/reduce.py
  neural_compressor/adaptor/ox_utils/operators/unary_op.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
Labels: enhancement

#1155 Easy to get started notebook of INC ONNXRT
  examples/notebook/onnxruntime/inc_sample_for_onnxruntime.ipynb
Labels: documentation, enhancement

#1145 GPTQ example refinements
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/quantization_weight_only.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/datautils.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run-gptq-llm.sh
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/gptq.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test_weight_only_quantization.py
Labels: bug fix

#1128 PT FX inspect tensor
  neural_compressor/adaptor/pytorch.py
  test/adaptor/pytorch_adaptor/test_adaptor_pytorch_1.x.py
Labels: new feature

#1160 Enhance ONNXRT backend check
  neural_compressor/adaptor/onnxrt.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
Labels: bug fix, enhancement

#1166 Add quick started notebook to examples README.md
  examples/README.md
  examples/notebook/onnxruntime/Quick_Started_Notebook_of_INC_for_ONNXRuntime.ipynb
Labels: documentation

#1148 add smooth_quant for layer-wise quant
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/quantize.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/utils.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/utils/pytorch.py
  test/algorithm/test_layer_wise_quant.py
Labels: enhancement

#928 Support per-channel MatMul quantization
  examples/tensorflow/nlp/bert_base_mrpc/quantization/ptq/README.md
  neural_compressor/adaptor/tensorflow.yaml
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_requantize.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
  neural_compressor/adaptor/tf_utils/graph_util.py
  neural_compressor/adaptor/tf_utils/quantize_graph_common.py
  test/tfnewapi/test_tensorflow_graph_qdq_matmul_fusion.py
Labels: enhancement, pending

#1163 Fix tf2.13.0 Keras model quantization failed issue
  docs/source/releases_info.md
  neural_compressor/adaptor/keras_utils/conv2d.py
  neural_compressor/adaptor/keras_utils/depthwise_conv2d.py
  neural_compressor/adaptor/keras_utils/separable_conv2d.py
Labels: bug fix

#1156 Fix awq issue
  neural_compressor/adaptor/ox_utils/weight_only.py
Labels: bug fix

#1183 fix layer-wise quant ut fail
  neural_compressor/adaptor/torch_utils/layer_wise_quant/utils.py
Labels: bug fix

#1176 update requirements version for tf2onnx
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
Labels: bug fix

#1168 Improve sq device mapping and enhance ut
  .azure-pipelines/scripts/ut/env_setup.sh
  .azure-pipelines/scripts/ut/run_basic_v2.1_ipex.sh
  .azure-pipelines/ut-basic-no-cover.yml
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/modeling_gptj.py
  test/algorithm/test_smooth_quant.py
Labels: enhancement

#1169 support conv1d pruning
  neural_compressor/compression/pruner/criteria.py
  neural_compressor/compression/pruner/patterns/base.py
  neural_compressor/compression/pruner/patterns/ninm.py
  neural_compressor/compression/pruner/patterns/nxm.py
  neural_compressor/experimental/pytorch_pruner/patterns.py
  test/pruning_with_pt/pruning_2.x/test_conv_pruning.py
Labels: new feature

#1179 Add distributed fallback by blockwise
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/strategy.py
Labels: enhancement

#1164 Fix tensorflow unit test redefinition issue
  test/adaptor/tensorflow_adaptor/test_tensorflow_graph_conv_fusion.py
  test/tfnewapi/test_tensorflow_graph_conv_fusion.py
  test/tfnewapi/test_tensorflow_graph_conv_requantize_fusion.py
  test/tfnewapi/test_tensorflow_graph_qdq_conv3d_fusion.py
Labels: bug fix

#1185 Support NF4/FP4 data type in weight-only
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/quantization_weight_only.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_clm.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/pytorch_cpu.yaml
  neural_compressor/adaptor/torch_utils/awq.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/config.py
  neural_compressor/model/torch_model.py
  neural_compressor/strategy/utils/constant.py
  neural_compressor/strategy/utils/tuning_space.py
  neural_compressor/strategy/utils/tuning_structs.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test.py
Labels: enhancement, new feature

#1188 Fix bugs in ONNXRT hf examples
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_quant.sh
Labels: bug fix

#1192 fix hpo example fail
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/hpo/run_glue_no_trainer.py
  neural_compressor/compression/hpo/search_algorithms.py
  test/hpo/test_hpo.py
Labels: bug fix

#1198 CI jobs title update and CVE fix
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/requirements.txt
  neural_compressor/benchmark.py
Labels: bug fix

#1197 Enhance ONNXRT adaptor and fix bugs
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/operators/concat.py
  neural_compressor/model/onnx_model.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: bug fix, enhancement
