Repository intel/neural-compressor, pull requests merged in 2023-07, with the labels that each got.

#1050 Update multimode distillation results
  docs/source/validated_model_list.md
Labels: documentation

#1035 add new adatptor doc
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/add_new_adaptor.md
  docs/source/user_guide.md
Labels: documentation

#1046 Adding jit trace to llm example
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py
Labels: enhancement

#1054 Reformat neural solution code
  neural_solution/__init__.py
  neural_solution/backend/__init__.py
  neural_solution/backend/cluster.py
  neural_solution/backend/result_monitor.py
  neural_solution/backend/runner.py
  neural_solution/backend/scheduler.py
  neural_solution/backend/task.py
  neural_solution/backend/task_db.py
  neural_solution/backend/task_monitor.py
  neural_solution/backend/utils/__init__.py
  neural_solution/backend/utils/utility.py
  neural_solution/bin/__init__.py
  neural_solution/bin/neural_solution.py
  neural_solution/config.py
  neural_solution/examples/custom_models_optimized/tf_example1/test.py
  neural_solution/frontend/fastapi/__init__.py
  neural_solution/frontend/fastapi/main_server.py
  neural_solution/frontend/gRPC/__init__.py
  neural_solution/frontend/gRPC/client.py
  neural_solution/frontend/gRPC/proto/__init__.py
  neural_solution/frontend/gRPC/proto/neural_solution_pb2.py
  neural_solution/frontend/gRPC/proto/neural_solution_pb2_grpc.py
  neural_solution/frontend/gRPC/server.py
  neural_solution/frontend/task_submitter.py
  neural_solution/frontend/utility.py
  neural_solution/launcher.py
  neural_solution/scripts/prepare_deps.py
  neural_solution/test/backend/test_cluster.py
  neural_solution/test/backend/test_result_monitor.py
  neural_solution/test/backend/test_runner.py
  neural_solution/test/backend/test_scheduler.py
  neural_solution/test/backend/test_task.py
  neural_solution/test/backend/test_task_db.py
  neural_solution/test/backend/test_task_monitor.py
  neural_solution/test/backend/utils/test_utility.py
  neural_solution/test/frontend/fastapi/test_main_server.py
  neural_solution/test/frontend/fastapi/test_task_submitter.py
  neural_solution/test/frontend/fastapi/test_utils.py
  neural_solution/test/test_logger.py
  neural_solution/utils/__init__.py
  neural_solution/utils/logger.py
  neural_solution/utils/utility.py
Labels: enhancement

#1048 Fix framework name in DataLoader API and refine dataloader & metric doc
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/dataloader.md
  docs/source/metric.md
  examples/onnxrt/nlp/bert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/bert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/distilbert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/distilbert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/main.py
  examples/onnxrt/nlp/mobilebert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/mobilebert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/gpt2.py
  examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/roberta/quantization/ptq_static/main.py
  neural_compressor/data/dataloaders/dataloader.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: documentation

#1044 Add diagram to introduce distributed tuning
  docs/source/imgs/distributed_tuning_intro.png
  docs/source/tuning_strategies.md
Labels: documentation

#1038 fix CVEs by update deps version
  neural_insights/gui/package-lock.json
  test/requirements.txt
Labels: bug fix

#998 Enable ViT
  examples/.config/model_params_tensorflow.json
  examples/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/run_benchmark.sh
  examples/tensorflow/image_recognition/tensorflow_models/vision_transformer/quantization/ptq/run_tuning.sh
  neural_compressor/data/__init__.py
  neural_compressor/data/transforms/__init__.py
  neural_compressor/data/transforms/imagenet_transform.py
Labels: examples

#1053 enable weight only quantization for language modeling
  docs/source/quantization_weight_only.md
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_clm.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_tuning.sh
Labels: examples, extension test

#1047 Fix Regression of TF ViT Pruning
  neural_compressor/compression/pruner/patterns.py
Labels: bug fix

#1051 Add quantized model download API for Neural Solution
  neural_solution/docs/source/description_api.md
  neural_solution/examples/custom_models_optimized/tf_example1/README.md
  neural_solution/examples/hf_models/README.md
  neural_solution/frontend/fastapi/main_server.py
  neural_solution/frontend/user_facing_api.json
Labels: new feature

#1066 Fix large_model judgement
  neural_compressor/model/onnx_model.py
Labels: bug fix

#1060 Neural Solution Resource Management
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  neural_solution/backend/cluster.py
  neural_solution/docs/source/README.md
  neural_solution/examples/custom_models_optimized/tf_example1/README.md
  neural_solution/examples/hf_models/README.md
  neural_solution/launcher.py
Labels: new feature

#1070 Update publications
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/publication_list.md
  neural_compressor/config.py
Labels: documentation

#1067 Remove distributed tuning flag from Unit Test
  test/strategy/test_distributed_tuning.py
Labels: bug fix

#1069 Support new spr-base version and fix version check issue
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tensorflow.yaml
  neural_compressor/adaptor/tf_utils/graph_converter.py
  neural_compressor/adaptor/tf_utils/graph_converter_without_calib.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/generic/convert_add_to_biasadd.py
  neural_compressor/adaptor/tf_utils/util.py
  test/tfnewapi/test_tensorflow_graph_conv_fusion.py
Labels: bug fix

#950 Introduce quant_level into mixed precision
  neural_compressor/config.py
  neural_compressor/strategy/auto_mixed_precision.py
  neural_compressor/strategy/utils/tuning_sampler.py
  test/mixed_precision/test_mixed_precision.py
Labels: enhancement

#1076 add WeightOnlyLinear for low memory inference.
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/model/torch_model.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test_weight_only_quantization.py
Labels: enhancement, new feature, WIP

#1074 Fixed the TF inspect tensor
  neural_compressor/adaptor/tensorflow.py
Labels: enhancement

#1059 Update the List of Supported Layers for Keras Mix-precision
  neural_compressor/adaptor/keras.yaml
Labels: enhancement

#1084 V2.2 release data
  docs/source/platform_configuration.md
  docs/source/validated_model_list.md
  examples/README.md
Labels: documentation

#1080 Update the Dataloader Usage of TF examples
  examples/keras/image_recognition/resnet50/quantization/ptq/README.md
  examples/keras/image_recognition/vgg16/quantization/ptq/README.md
  examples/keras/image_recognition/vgg19/quantization/ptq/README.md
  examples/tensorflow/image_recognition/SavedModel/efficientnet_v2_b0/quantization/ptq/main.py
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/main.py
  examples/tensorflow/image_recognition/resnet_v2/pruning/magnitude/main.py
  examples/tensorflow/image_recognition/resnet_v2/quantization/qat/main.py
  examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_resnet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v4/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v3/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/mixed_precision/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_152/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_50/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg19/quantization/ptq/main.py
  examples/tensorflow/nlp/bert_base_mrpc/quantization/ptq/run_classifier.py
  examples/tensorflow/nlp/bert_large_squad/quantization/ptq/tune_squad.py
  examples/tensorflow/nlp/bert_large_squad_model_zoo/quantization/ptq/tune_squad.py
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/run_inference.py
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/main.py
  examples/tensorflow/nlp/transformer_lt/quantization/ptq/main.py
  examples/tensorflow/nlp/transformer_lt_mlperf/quantization/ptq/run_inference.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/mask_rcnn_inception_v2/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/main.py
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/infer_detections.py
  examples/tensorflow/recommendation/wide_deep_large_ds/quantization/ptq/inference.py
  examples/tensorflow/style_transfer/arbitrary_style_transfer/quantization/ptq/style_tune.py
Labels: examples

#1062 Fixed the objective initialization issue
  docs/source/objective.md
  neural_compressor/config.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/strategy.py
  test/strategy/test_quant_level.py
Labels: bug fix

#1061 Fix ONNXRT diagnosis bug
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/adaptor/ox_utils/smooth_quant.py
  neural_compressor/model/onnx_model.py
  test/model/test_onnx_model.py
Labels: bug fix

#1045 Enable GPTQ for LLM quantization
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/gptq.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test_weight_only_quantization.py
Labels: new feature

#903 Add dnnl ep
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/mixed_precision.md
  docs/source/quantization.md
  examples/onnxrt/nlp/huggingface_model/text_classification/mix_precision/README.md
  examples/onnxrt/nlp/huggingface_model/text_classification/mix_precision/eval.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/mix_precision/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/mix_precision/prepare_data.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/mix_precision/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_classification/mix_precision/run.sh
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/onnxrt_dnnl.yaml
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/config.py
  neural_compressor/mix_precision.py
  neural_compressor/model/model.py
  neural_compressor/strategy/strategy.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
Labels: new feature

#1083 support full range for 4 bit sym -8
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/config.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
Labels: bug fix, enhancement, WIP

#1090 Included `add` to O0's quant op type list
  neural_compressor/strategy/conservative.py
  test/ipex/test_adaptor_ipex.py
Labels: enhancement

#1036 pruning/refactor
  neural_compressor/compression/pruner/__init__.py
  neural_compressor/compression/pruner/criteria.py
  neural_compressor/compression/pruner/patterns.py
  neural_compressor/compression/pruner/patterns/__init__.py
  neural_compressor/compression/pruner/patterns/base.py
  neural_compressor/compression/pruner/patterns/mha.py
  neural_compressor/compression/pruner/patterns/ninm.py
  neural_compressor/compression/pruner/patterns/nxm.py
  neural_compressor/compression/pruner/pruners.py
  neural_compressor/compression/pruner/pruners/__init__.py
  neural_compressor/compression/pruner/pruners/base.py
  neural_compressor/compression/pruner/pruners/basic.py
  neural_compressor/compression/pruner/pruners/block_mask.py
  neural_compressor/compression/pruner/pruners/mha.py
  neural_compressor/compression/pruner/pruners/pattern_lock.py
  neural_compressor/compression/pruner/pruners/progressive.py
  neural_compressor/compression/pruner/pruners/retrain_free.py
  neural_compressor/compression/pruner/regs.py
  neural_compressor/compression/pruner/schedulers.py
  neural_compressor/compression/pruner/tf_criteria.py
  neural_compressor/compression/pruner/utils.py
  neural_compressor/config.py
  test/pruning_2.x/test_pruning.py
  test/pruning_2.x/test_pruning_keras.py
Labels: WIP

#1105 Enhance strategy exit policy
  neural_compressor/experimental/strategy/strategy.py
  neural_compressor/strategy/auto.py
  neural_compressor/strategy/strategy.py
  test/strategy/test_quant_level.py
Labels: bug fix, enhancement

#1107 CI UT adjust to reduce overall time consume
  .azure-pipelines/scripts/ut/collect_log.sh
  .azure-pipelines/scripts/ut/run_basic_ipex.sh
  .azure-pipelines/scripts/ut/run_basic_others.sh
  .azure-pipelines/scripts/ut/run_basic_pruning.sh
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
Labels: validation

#1094 Documentation enhance for Calibration algorithm
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/calibration.md
  docs/source/user_guide.md
Labels: documentation

#1089 Add ONNX layoutlmv2
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/export.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/funsd.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/image_utils.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/export.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/funsd.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/image_utils.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv2/quantization/ptq_static/run_tuning.sh
Labels: examples

#786 add Hyper-parameter Optimization algorithm
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/pruning.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/hpo/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/hpo/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/hpo/run_glue_no_trainer.py
  neural_compressor/compression/hpo/__init__.py
  neural_compressor/compression/hpo/sa_optimizer.py
  neural_compressor/compression/hpo/search_algorithms.py
  neural_compressor/compression/hpo/search_space.py
  neural_compressor/compression/pruner/README.md
  neural_compressor/config.py
  test/hpo/test_hpo.py
  test/requirements.txt
Labels: new feature

#1109 Enhance SmoothQuant tuning structure.
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tf_utils/smooth_quant_scaler.py
  neural_compressor/adaptor/tf_utils/util.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/algorithm/smooth_quant.py
  neural_compressor/config.py
  neural_compressor/strategy/auto.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/tuning_sampler.py
  neural_compressor/strategy/utils/utility.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
  test/algorithm/test_smooth_quant.py
  test/quantization/test_weight_only_quantization.py
Labels: enhancement, new feature, WIP

#1106 introduce export_compressed_model API
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/quantization_weight_only.md
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
Labels: documentation
