Repository intel/neural-compressor, pull requests merged in 2023-03, with the labels that each got.

#601 Fix IPEX config json changed according to tune_cfg
  neural_compressor/adaptor/torch_utils/util.py
Labels: bug fix

#521 support keras functional model and tuning fallback layers
  examples/.config/model_params_keras.json
  examples/README.md
  examples/keras/image_recognition/imagenet_prepare/build_imagenet_data.py
  examples/keras/image_recognition/imagenet_prepare/download_and_convert_imagenet.sh
  examples/keras/image_recognition/imagenet_prepare/download_imagenet.sh
  examples/keras/image_recognition/imagenet_prepare/imagenet_lsvrc_2015_synsets.txt
  examples/keras/image_recognition/imagenet_prepare/imagenet_metadata.txt
  examples/keras/image_recognition/mnist/README.md
  examples/keras/image_recognition/mnist/mnist.py
  examples/keras/image_recognition/mnist/requirements.txt
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/README.md
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/main.py
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/prepare_model.py
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/run_benchmark.sh
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/run_tuning.sh
  examples/keras/image_recognition/prepare_dataset.sh
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/README.md
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/main.py
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/prepare_model.py
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/run_benchmark.sh
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/run_tuning.sh
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/README.md
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/main.py
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/prepare_model.py
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/run_benchmark.sh
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/run_tuning.sh
  examples/keras/image_recognition/xception/quantization/ptq/README.md
  examples/keras/image_recognition/xception/quantization/ptq/main.py
  examples/keras/image_recognition/xception/quantization/ptq/prepare_model.py
  examples/keras/image_recognition/xception/quantization/ptq/run_benchmark.sh
  examples/keras/image_recognition/xception/quantization/ptq/run_tuning.sh
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/inception_resnet_v2/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/inception_v3/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/mobilenet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/keras_models/resnet101/quantization/ptq/prepare_model.py
  examples/tensorflow/image_recognition/keras_models/xception/quantization/ptq/README.md
  neural_compressor/adaptor/keras.py
  neural_compressor/adaptor/keras_utils/conv2d.py
  neural_compressor/adaptor/keras_utils/dense.py
  neural_compressor/adaptor/keras_utils/quantizer.py
  neural_compressor/model/keras_model.py
  neural_compressor/model/model.py
  test/itex/test_keras_in_keras_out.py
Labels: enhancement, review, examples, extension test

#522 add user guide about the code migration
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/migration.md
  docs/source/user_guide.md
Labels: documentation, review

#615 fix imagenet dataset prepare path
  examples/helloworld/tf_example1/README.md
  examples/helloworld/tf_example5/README.md
  examples/helloworld/tf_example6/README.md
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v2/quantization/ptq/README.md
Labels: documentation

#586 Update DyNAS-T Interface
  examples/notebook/dynas/BERT_SST2_Supernet_NAS.ipynb
  examples/notebook/dynas/MobileNetV3_Supernet_Distributed_NAS.ipynb
  examples/notebook/dynas/MobileNetV3_Supernet_NAS.ipynb
  examples/notebook/dynas/Transformer_LT_Supernet_NAS.ipynb
  examples/notebook/dynas/distributed_example.py
  examples/notebook/dynas/results_bertbase_sst2_macs.csv
  neural_compressor/conf/config.py
  neural_compressor/experimental/nas/dynas.py
  neural_compressor/experimental/nas/dynast/__init__.py
  neural_compressor/experimental/nas/dynast/dynas_manager.py
  neural_compressor/experimental/nas/dynast/dynas_predictor.py
  neural_compressor/experimental/nas/dynast/dynas_search.py
  neural_compressor/experimental/nas/dynast/dynas_utils.py
  neural_compressor/experimental/nas/dynast/supernetwork/__init__.py
  neural_compressor/experimental/nas/dynast/supernetwork/machine_translation/__init__.py
  neural_compressor/experimental/nas/dynast/supernetwork/machine_translation/modules_supernetwork.py
  neural_compressor/experimental/nas/dynast/supernetwork/machine_translation/transformer_interface.py
  neural_compressor/experimental/nas/dynast/supernetwork/machine_translation/transformer_supernetwork.py
  test/nas/test_nas.py
  test/requirements.txt
Labels: new feature

#614 Pruner/refine docs examples
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/run_glue_no_trainer.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/run_glue_no_trainer_mixed.py
  examples/pytorch/object_detection/yolo_v5/pruning/eager/train.py
  neural_compressor/compression/pruner/README.md
  neural_compressor/compression/pruner/regs.py
  neural_compressor/compression/pruner/utils.py
Labels: documentation

#619 minor fix for CI workspace clean
  .azure-pipelines/template/docker-template.yml
  .azure-pipelines/ut-ncoder.yml
  .azure-pipelines/ut-ux.yml
  neural_compressor/version.py
Labels: validation

#610 migrate translation and peleenet examples
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/LICENSE
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/PeleeNet_README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/main.py
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/peleenet.py
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/requirements.txt
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_benchmark.sh
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_translation.py
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_tuning.sh
Labels: examples, extension test

#574 add distributed tuning doc
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/tuning_strategies.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/strategy.py
  test/strategy/test_distributed_tuning.py
Labels: documentation, review, WIP

#613 smooth quant example update
  examples/.config/model_params_pytorch.json
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/requirements.txt
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/smooth_quant/README.md
Labels: documentation, examples, extension test

#563 add two export examples to validate accuracy and performance of export API.
  docs/source/export.md
  examples/.config/model_params_pt2onnx.json
  examples/pytorch/image_recognition/torchvision_models/export/fx/README.md
  examples/pytorch/image_recognition/torchvision_models/export/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/export/fx/onnx_evaluation.py
  examples/pytorch/image_recognition/torchvision_models/export/fx/requirements.txt
  examples/pytorch/image_recognition/torchvision_models/export/fx/run_benchmark.sh
  examples/pytorch/image_recognition/torchvision_models/export/fx/run_export.sh
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/onnx_evaluation.py
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_export.sh
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py
  neural_compressor/conf/config.py
  neural_compressor/experimental/export/torch2onnx.py
Labels: examples, extension test

#611 add models to NLP example
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/qat/fx/README.md
Labels: examples, extension test

#573 TF CI support new API
  .azure-pipelines/model-test.yml
  .azure-pipelines/scripts/models/collect_log_model.py
  .azure-pipelines/scripts/models/run_benchmark_common.sh
  .azure-pipelines/scripts/models/run_model_trigger_common.sh
  .azure-pipelines/scripts/models/run_tensorflow_models_trigger.sh
  .azure-pipelines/scripts/models/run_tuning_common.sh
  examples/tensorflow/image_recognition/tensorflow_models/inception_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/main.py
Labels: validation

#621 improve quantization speed for LLM
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/strategy/utils/tuning_space.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: enhancement

#622 ResNet50 pruning example with INC new API.
  docs/source/imgs/pruning/scatter-03-09.png
  docs/source/validated_model_list.md
  examples/README.md
  examples/pytorch/image_recognition/ResNet50/pruning/eager/README.md
  examples/pytorch/image_recognition/ResNet50/pruning/eager/requirements.txt
  examples/pytorch/image_recognition/ResNet50/pruning/eager/run_resnet50_prune.sh
  examples/pytorch/image_recognition/ResNet50/pruning/eager/train.py
  examples/pytorch/image_recognition/torchvision_models/pruning/magnitude/eager/README.md
  examples/pytorch/image_recognition/torchvision_models/pruning/magnitude/eager/main.py
  examples/pytorch/image_recognition/torchvision_models/pruning/magnitude/eager/requirements.txt
  examples/pytorch/image_recognition/torchvision_models/pruning/magnitude/eager/run_pruning_cpu.sh
  examples/pytorch/image_recognition/torchvision_models/pruning/magnitude/eager/run_pruning_distributed_cpu.sh
  neural_compressor/compression/pruner/README.md
Labels: examples, extension test

#627 Adapt to PyTorch 2.0 version
  neural_compressor/adaptor/pytorch.py
  neural_compressor/model/torch_model.py
  neural_compressor/training.py
  neural_compressor/utils/pytorch.py
  neural_compressor/utils/utility.py
  test/adaptor/pytorch_adaptor/test_adaptor_pytorch_1.x.py
  test/adaptor/pytorch_adaptor/test_adaptor_pytorch_2.x.py
Labels: enhancement, extension test

#600 Fix tf2onnx int8 performance issue
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/main.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/onnx/onnx_graph.py
  neural_compressor/adaptor/tf_utils/tf2onnx_converter.py
  neural_compressor/experimental/export/tf2onnx.py
  test/itex/test_tensorflow_qdq_convert_to_onnx_qdq.py
Labels: bug fix, extension test

#623 Improve transform and metric UT
  neural_compressor/experimental/metric/metric.py
  test/data/test_exp_transformers.py
  test/metric/test_exp_metrics.py
Labels: enhancement

#624 Fix some HF models exit without tuning
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  neural_compressor/conf/config.py
  neural_compressor/quantization.py
  neural_compressor/strategy/auto.py
  test/strategy/test_basic.py
  test/strategy/test_optimization_level_2.x.py
  test/strategy/test_quant_level.py
Labels: bug fix, extension test

#628 Fix mix precision
  docs/source/mixed_precision.md
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/config.py
  neural_compressor/mix_precision.py
  test/mixed_precision/test_mixed_precision.py
Labels: enhancement

#650 Fix ort adaptor
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/util.py
Labels: bug fix

#657 fix error of building doc and user guide link issue
  README.md
  docs/build_docs/build.sh
  docs/source/api-doc/adaptor/torch_utils.rst
  docs/source/api-doc/adaptor/torch_utils/onnx.rst
  docs/source/user_guide.md
Labels: documentation

#640 Enhancement of Pruning Documentation
  docs/source/imgs/pruning/progressive_pruning.png
  docs/source/imgs/pruning/pruning_scatter.jpg
  docs/source/imgs/pruning/pruning_scatter.png
  docs/source/pruning.md
  docs/source/pruning_details.md
  neural_compressor/compression/pruner/README.md
Labels: documentation, review

#645 Fix tensorflow dataloader issue
  neural_compressor/data/dataloaders/tensorflow_dataloader.py
Labels: bug fix

#629 add weight for fx_model and fix export bug
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/experimental/export/torch2onnx.py
  neural_compressor/utils/pytorch.py
  test/export/test_torch2onnx.py
Labels: enhancement

#669 Fixed case error for without tuning
  neural_compressor/quantization.py
Labels: bug fix, review

#664 Enhance UTs for strategies
  neural_compressor/strategy/conservative.py
  neural_compressor/strategy/mse_v2.py
  test/adaptor/pytorch_adaptor/test_adaptor_pytorch_2.x.py
  test/strategy/test_hawq_v2_2.x.py
Labels: bug fix, validation

#641 modify auto-api template
  docs/build_docs/source/autoapi_templates/python/class.rst
  docs/build_docs/source/conf.py
  docs/build_docs/update_html.py
  docs/source/api-doc/adaptor/onnxrt.rst
  docs/source/api-doc/adaptor/torch_utils.rst
  docs/source/api-doc/adaptor/torch_utils/bf16_convert.rst
  docs/source/api-doc/adaptor/torch_utils/hawq_metric.rst
  docs/source/api-doc/adaptor/torch_utils/symbolic_trace.rst
  docs/source/api-doc/adaptor/torch_utils/util.rst
  docs/source/api-doc/algorithm.rst
  docs/source/api-doc/api_doc_example.rst
  docs/source/api-doc/apis.rst
  docs/source/api-doc/basic_api.rst
  docs/source/api-doc/benchmark.rst
  docs/source/api-doc/common.rst
  docs/source/api-doc/common/benchmark.rst
  docs/source/api-doc/common/bleu.rst
  docs/source/api-doc/common/criterion.rst
  docs/source/api-doc/common/data.rst
  docs/source/api-doc/common/data/dataloader.rst
  docs/source/api-doc/common/data/datasets.rst
  docs/source/api-doc/common/data/transforms.rst
  docs/source/api-doc/common/metric.rst
  docs/source/api-doc/common/model.rst
  docs/source/api-doc/common/optimizer.rst
  docs/source/api-doc/component.rst
  docs/source/api-doc/component/Distillation.rst
  docs/source/api-doc/component/MixedPrecision.rst
  docs/source/api-doc/component/ModelConversion.rst
  docs/source/api-doc/component/Nas.rst
  docs/source/api-doc/component/Pruning.rst
  docs/source/api-doc/component/Quantization.rst
  docs/source/api-doc/component/Scheduler.rst
  docs/source/api-doc/compression.rst
  docs/source/api-doc/config.rst
  docs/source/api-doc/contrib.rst
  docs/source/api-doc/mix_precision.rst
  docs/source/api-doc/model.rst
  docs/source/api-doc/objective.rst
  docs/source/api-doc/pythonic.rst
  docs/source/api-doc/quantization.rst
  docs/source/api-doc/strategy.rst
  docs/source/api-doc/strategy/strategy.rst
  docs/source/api-doc/training.rst
  docs/source/api-doc/utils.rst
  neural_compressor/adaptor/torch_utils/hawq_metric.py
  neural_compressor/benchmark.py
  neural_compressor/config.py
  neural_compressor/data/datasets/bert_dataset.py
  neural_compressor/experimental/data/datasets/bert_dataset.py
  neural_compressor/mix_precision.py
  neural_compressor/objective.py
  neural_compressor/quantization.py
  neural_compressor/template/__init__.py
  neural_compressor/template/api_doc_example.py
  neural_compressor/training.py
  neural_compressor/ux/utils/proc.py
Labels: documentation

#699 Remove onnx/onnxruntime version limit
  examples/onnxrt/image_recognition/mobilenet_v2/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/mobilenet_v3/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/onnx_model_zoo/alexnet/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/onnx_model_zoo/caffenet/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/onnx_model_zoo/densenet/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/onnx_model_zoo/efficientnet/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/onnx_model_zoo/googlenet/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/onnx_model_zoo/inception/quantization/ptq_static/requirements.txt
Labels: examples

#684 refine smooth quant readme
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
Labels: documentation

#697 Pruner doc fix
  neural_compressor/compression/pruner/README.md
Labels: documentation, review

#647 Refined distillation document.
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/distillation.md
Labels: documentation, review

#686 fix orchestration error of cv examples
  examples/README.md
  examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/prune_and_ptq/fx/README.md
  examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/prune_and_ptq/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/qat_during_prune/fx/README.md
  examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/qat_during_prune/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/optimization_pipeline/qat_during_prune/fx/requirements.txt
  neural_compressor/model/keras_model.py
  neural_compressor/model/tensorflow_model.py
  neural_compressor/model/torch_model.py
Labels: bug fix

#698 Fix pytorch windows benchmark issue
  neural_compressor/benchmark.py
Labels: bug fix

#638 Update the doc for tuning strategy
  docs/source/tuning_strategies.md
Labels: documentation

#701 Add orchestration UT case with distillation, pruning and qat
  test/scheduler/test_orchestration.py
Labels: validation

#706 Update the configuration of examples using mse_v2
  examples/pytorch/image_recognition/torchvision_models/export/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py
Labels: bug fix

#683 Support UT Coverage Improvement of TF Backend
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tf_utils/graph_converter.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/freeze_fake_quant.py
  neural_compressor/adaptor/tf_utils/quantize_graph/qat/quantize_config.py
  neural_compressor/adaptor/tf_utils/quantize_graph/qat/quantize_helper.py
  neural_compressor/adaptor/tf_utils/quantize_graph/qat/quantize_wrapper.py
  neural_compressor/adaptor/tf_utils/util.py
  neural_compressor/experimental/model_conversion.py
  neural_compressor/model/keras_model.py
  neural_compressor/model/tensorflow_model.py
  test/adaptor/tensorflow_adaptor/test_tensorflow_data_pipline.py
  test/adaptor/tensorflow_adaptor/test_tensorflow_graph_dequantize_cast_optimizer.py
  test/adaptor/tensorflow_adaptor/test_tf_util.py
  test/model/test_model.py
  test/model/test_model_conversion.py
  test/quantization/test_tensorflow_qat.py
Labels: bug fix, validation

#709 Improve UT coverage and fix bug
  neural_compressor/adaptor/ox_utils/operators/concat.py
  neural_compressor/adaptor/ox_utils/operators/ops.py
  neural_compressor/adaptor/ox_utils/operators/split.py
  neural_compressor/conf/pythonic_config.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
  test/config/test_pythonic_config.py
  test/data/test_exp_dataloader.py
Labels: bug fix

#707 enhance resnet50 pruning examples
  examples/pytorch/image_recognition/ResNet50/pruning/eager/README.md
  examples/pytorch/image_recognition/ResNet50/pruning/eager/run_resnet50_prune.sh
  examples/pytorch/image_recognition/ResNet50/pruning/eager/train.py
Labels: bug fix, examples

#721 Fixed O0
  neural_compressor/strategy/conservative.py
  neural_compressor/strategy/utils/constant.py
Labels: bug fix

#720 Disable bf16 mixed precision on non-bf16 machine for TF
  neural_compressor/adaptor/tf_utils/graph_converter.py
Labels: bug fix

#714 Update coco dataset path in ort obj detection example
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/faster_rcnn/quantization/ptq_static/main.py
  examples/onnxrt/object_detection/onnx_model_zoo/mask_rcnn/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/mask_rcnn/quantization/ptq_static/main.py
  examples/onnxrt/object_detection/onnx_model_zoo/ssd/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/ssd/quantization/ptq_static/data_utils.py
  examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/ssd_mobilenet_v1/quantization/ptq_static/data_utils.py
  examples/onnxrt/object_detection/onnx_model_zoo/tiny_yolov3/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/tiny_yolov3/quantization/ptq_static/main.py
  examples/onnxrt/object_detection/onnx_model_zoo/yolov3/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/yolov3/quantization/ptq_static/main.py
  examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/onnx_model_zoo/yolov4/quantization/ptq_static/main.py
  examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/data_utils.py
  examples/onnxrt/object_detection/ssd_mobilenet_v2/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/ssd_mobilenet_v2/quantization/ptq_static/data_utils.py
Labels: examples

#696 Updated Notebook for INC 2.0
  examples/notebook/tensorflow/vgg19_ibean/conda_set_env.sh
  examples/notebook/tensorflow/vgg19_ibean/devcloud_setup_env.sh
  examples/notebook/tensorflow/vgg19_ibean/inc_quantize_model.py
  examples/notebook/tensorflow/vgg19_ibean/inc_quantize_vgg19.ipynb
  examples/notebook/tensorflow/vgg19_ibean/pip_set_env.sh
  examples/notebook/tensorflow/vgg19_ibean/run_in_intel_devcloud.sh
  examples/notebook/tensorflow/vgg19_ibean/vgg19.yaml
Labels: review

#716 INC Bench documentation update
  docs/source/bench.md
  docs/source/imgs/bench/diagnosis-tab.jpg
  docs/source/imgs/bench/diagnosis-tab.png
  docs/source/imgs/bench/graph-resnet.jpg
  docs/source/imgs/bench/graph_bert.png
  docs/source/imgs/bench/histogram.jpg
Labels: documentation

#722 Improve quantization document
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/quantization.md
  neural_compressor/quantization.py
Labels: documentation

#719 change assert to warning
  neural_compressor/utils/pytorch.py
Labels: bug fix

#727 Fix ITEX oneDNN graph crash issue for MaxPool QDQ dtype mismatch
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
Labels: bug fix

#682 Fix the Tuning issue of helloworld tf_example2
  examples/helloworld/tf_example2/README.md
  examples/helloworld/tf_example2/requirements.txt
  examples/helloworld/tf_example2/test.py
  examples/keras/image_recognition/mnist/README.md
  examples/keras/image_recognition/mnist/mnist.py
  examples/keras/image_recognition/mnist/requirements.txt
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/README.md
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/main.py
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/README.md
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/main.py
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/README.md
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/main.py
  examples/keras/image_recognition/xception/quantization/ptq/README.md
  examples/keras/image_recognition/xception/quantization/ptq/main.py
  neural_compressor/adaptor/keras.py
Labels: bug fix, examples

#702 add smooth quant doc
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  docs/source/imgs/smoothquant.png
  docs/source/smooth_quant.md
  docs/source/user_guide.md
Labels: documentation, review

#725 Add log for bfloat16 data type for PyTorch framework
  neural_compressor/adaptor/torch_utils/bf16_convert.py
Labels: enhancement

#713 Pruning code coverage ut-test modification
  neural_compressor/experimental/pruning_v2.py
  neural_compressor/experimental/pytorch_pruner/logger.py
  test/pruning_1.x_v2/test_tensorflow_pruning.py
Labels: validation

#730 Fix ORT query fw capability
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/model/onnx_model.py
  neural_compressor/strategy/utils/constant.py
Labels: bug fix

#735 Refine ORT example doc
  examples/onnxrt/nlp/bert/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/bert/quantization/ptq_static/README.md
  examples/onnxrt/nlp/distilbert/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/distilbert/quantization/ptq_static/README.md
  examples/onnxrt/nlp/mobilebert/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/mobilebert/quantization/ptq_static/README.md
  examples/onnxrt/nlp/onnx_model_zoo/BiDAF/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/onnx_model_zoo/BiDAF/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/export.py
  examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/export.py
  examples/onnxrt/nlp/roberta/quantization/ptq_static/README.md
  examples/onnxrt/nlp/roberta/quantization/ptq_static/export.py
Labels: documentation, examples

#732 Fix ORT example doc
  examples/onnxrt/body_analysis/onnx_model_zoo/arcface/quantization/ptq_static/README.md
  examples/onnxrt/body_analysis/onnx_model_zoo/emotion_ferplus/quantization/ptq_static/README.md
  examples/onnxrt/body_analysis/onnx_model_zoo/ultraface/quantization/ptq_static/README.md
Labels: documentation

#737 Add Keras to the Framework Checklist
  neural_compressor/data/dataloaders/dataloader.py
  neural_compressor/data/datasets/dataset.py
  neural_compressor/data/filters/filter.py
  neural_compressor/data/transforms/transform.py
  neural_compressor/experimental/data/datasets/dataset.py
  neural_compressor/experimental/data/filters/filter.py
  neural_compressor/experimental/data/transforms/transform.py
  neural_compressor/experimental/metric/metric.py
  neural_compressor/metric/metric.py
Labels: bug fix

#738 fixed typo for log
  neural_compressor/adaptor/ox_utils/quantizer.py
Labels: bug fix

#736 fixed ofa stage2 model load error and updated readme
  examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/run_qa_no_trainer_pruneOFA.py
Labels: bug fix, examples

#729 quantization/sq support more patterns
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix, enhancement

#733 minor fix for pytorch examples
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/.dockerignore
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/.gitignore
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/3DUnet_README.md
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/Makefile
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/README.md
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/Task043_BraTS_2019.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/accuracy-brats.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/brats_QSL.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/brats_cal_images_list.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold0_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold1_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold2_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold3_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold4_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/mlperf.conf
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/onnxruntime_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/ov_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/preprocess.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/pytorch_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/requirements.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/run.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/run_benchmark.sh
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/run_tuning.sh
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/tf_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/unet_onnx_to_tf.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/unet_pytorch_to_onnx.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/user.conf
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/LICENSE
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/PeleeNet_README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/main.py
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/peleenet.py
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/requirements.txt
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_benchmark.sh
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_tuning.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
  examples/pytorch/nlp/huggingface_models/summarization/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/summarization/quantization/ptq_dynamic/fx/run_summarization.py
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_translation.py
  examples/pytorch/nlp/huggingface_models/translation/quantization/ptq_dynamic/fx/run_tuning.sh
Labels: bug fix, extension test

#748 Docstring polish
  neural_compressor/config.py
Labels: documentation

#746 Fixed issue of dataloader not prepared before evaluation.
  examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/run_qa_no_trainer_pruneOFA.py
Labels: bug fix, examples

#752 BenchmarkConfig/TF2ONNXConfig docstring polish
  neural_compressor/config.py
Labels: documentation

#754 fix torchaudio example requirements
  examples/pytorch/speech_recognition/torchaudio_models/quantization/ptq_static/fx/requirements.txt
Labels: examples, extension test

#755 Rename private class
  docs/source/migration.md
  neural_compressor/__init__.py
  neural_compressor/benchmark.py
  neural_compressor/conf/pythonic_config.py
  neural_compressor/config.py
  neural_compressor/mix_precision.py
  neural_compressor/quantization.py
Labels: bug fix

#750 Pruning config docstring polish
  neural_compressor/config.py
Labels: documentation

#757 ExportConfig&Torch2ONNXConfig docstring polish
  neural_compressor/config.py
Labels: documentation

#747 smoothquant alpha auto-tuning
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/config.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/tuning_sampler.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
  test/algorithm/test_smooth_quant.py
Labels: new feature

#745 Improve docstring of config.py
  neural_compressor/config.py
Labels: documentation, enhancement

#763 update main page readme
  .azure-pipelines/scripts/models/run_benchmark_common.sh
  README.md
  docs/source/validated_model_list.md
Labels: documentation

#751 Support inserting QDQ pair for BN+Relu and BN+Relu6 fusion pattern on ITEX mode
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/generic/insert_print_node.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/freeze_value.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
Labels: new feature
