Repository intel/neural-compressor, pull requests merged in 2023-05, with the labels that each got.

#823 update qconfig to meet ipex2.1 requirement and fix ipex bugs
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/adaptor/torch_utils/util.py
  test/algorithm/test_smooth_quant.py
  test/ipex/test_adaptor_ipex.py
Labels: bug fix, enhancement

#837 Enable ONNXRT layoutlmft & layoutlmv3 examples
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/model.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/run_tuning.sh
  neural_compressor/adaptor/ox_utils/calibrator.py
  neural_compressor/strategy/strategy.py
Labels: examples, extension test

#860 modify neural coder cve
  neural_coder/extensions/neural_compressor_ext_lab/neural_compressor_ext_lab/labextension/package-lock.json
  neural_coder/extensions/neural_compressor_ext_lab/neural_compressor_ext_lab/labextension/package.json
  neural_coder/extensions/neural_compressor_ext_lab/package-lock.json
  neural_coder/extensions/neural_compressor_ext_lab/package.json
  neural_coder/extensions/neural_compressor_ext_lab_alibaba/package-lock.json
  neural_coder/extensions/neural_compressor_ext_lab_alibaba/package.json
Labels: bug fix

#851 fix document, example readme and code
  docs/source/smooth_quant.md
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/README.md
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/README.md
Labels: bug fix

#863 Specify ONNX model zoo in validated model list
  docs/source/validated_model_list.md
  examples/README.md
Labels: documentation

#871 CI FWs version update
  .azure-pipelines/scripts/models/env_setup.sh
  .azure-pipelines/scripts/models/run_onnxrt_models_trigger.sh
  .azure-pipelines/scripts/models/run_pytorch_models_trigger.sh
  .azure-pipelines/scripts/models/run_tensorflow_models_trigger.sh
  .azure-pipelines/scripts/ut/env_setup.sh
  .azure-pipelines/scripts/ut/ut_fwk_version.sh
Labels: validation

#852 Enable progressive pruning in N:M pattern
  neural_compressor/compression/pruner/patterns.py
  neural_compressor/compression/pruner/pruners.py
  test/pruning_2.x/test_pruning_progressive.py
Labels: new feature

#835 Enable more Ops for Keras PTQ and Support Mix-precision
  neural_compressor/adaptor/keras.py
  neural_compressor/adaptor/keras.yaml
  neural_compressor/adaptor/keras_utils/pool2d.py
  test/mixed_precision/test_mixed_precision_keras_model.py
Labels: enhancement

#859 Adapt Neural Coder to INC New API Pytorch part
  neural_coder/backends/pytorch_inc_bf16.yaml
  neural_coder/backends/pytorch_inc_dynamic_quant.yaml
  neural_coder/backends/pytorch_inc_dynamic_quant_fp8.yaml
  neural_coder/backends/pytorch_inc_static_quant_fx.yaml
  neural_coder/backends/pytorch_inc_static_quant_fx_fp8.yaml
  neural_coder/backends/pytorch_inc_static_quant_ipex.yaml
  neural_coder/extensions/neural_compressor_ext_lab/lib/test.js
Labels: enhancement

#858 Adapt Neural Coder to INC New API TF and ONNX part
  neural_coder/backends/keras_inc.yaml
  neural_coder/backends/onnx_inc_dynamic_quant.yaml
  neural_coder/backends/onnx_inc_static_quant_qdq.yaml
  neural_coder/backends/onnx_inc_static_quant_qlinear.yaml
  neural_coder/coders/tensorflow/inc.py
Labels: enhancement

#868 Fix Regression of Helloworld Example tf_example7
  examples/helloworld/tf_example7/README.md
  examples/helloworld/tf_example7/test.py
Labels: bug fix, extension test

#867 Fix bugs when automatically exclude classifier heads in pruning.
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  test/pruning_2.x/test_auto_excluding_classifier.py
Labels: bug fix, extension test

#861 remove redundant attribute
  neural_compressor/config.py
  test/config/test_config_2.x.py
Labels: bug fix

#877 fix ipex adaptor remaining issue
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/util.py
Labels: bug fix

#880 install official tensorflow 2.12 for CI test
  .azure-pipelines/scripts/ut/ut_fwk_version.sh
Labels: validation

#818 Block-wise tuning for PyTorch model
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/requirements.txt
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/pattern_detector.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/utils/tuning_sampler.py
  test/adaptor/pytorch_adaptor/test_adaptor_pytorch_2.x.py
  test/strategy/test_basic.py
  test/strategy/test_tuning_sampler.py
Labels: new feature

#873 Fix fold scale bug
  neural_compressor/adaptor/ox_utils/util.py
Labels: bug fix, extension test

#888 Optimize the Running time of Keras Mix-precision UTs
  test/distillation/test_distillation_2.x.py
  test/mixed_precision/test_mixed_precision_keras_model.py
Labels: validation

#889 limit TF version for TF distribute test
  .azure-pipelines/scripts/ut/run_basic_adaptor.sh
  .azure-pipelines/scripts/ut/run_basic_adaptor_tfnewapi.sh
  .azure-pipelines/scripts/ut/run_basic_ipex.sh
  .azure-pipelines/scripts/ut/run_basic_itex.sh
  .azure-pipelines/scripts/ut/run_basic_others.sh
  .azure-pipelines/scripts/ut/run_basic_pruning.sh
  .azure-pipelines/scripts/ut/run_ncoder.sh
  .azure-pipelines/scripts/ut/run_ux.sh
  .azure-pipelines/scripts/ut/ut_fwk_version.sh
  test/distributed/test_distributed_metrics.py
Labels: validation

#855 Enhance distributed tuning
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/tuning_strategies.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py
  neural_compressor/conf/config.py
  neural_compressor/conf/pythonic_config.py
  neural_compressor/config.py
  neural_compressor/experimental/quantization.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/utility.py
  test/strategy/test_basic_1.x.py
  test/strategy/test_utility.py
Labels: enhancement

#865 Support msev2 for onnxrt adaptor
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/quantization.py
  test/strategy/test_mse_v2_2.x.py
Labels: new feature

#902 resolve memory issue
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix

#901 Refine PT2ONNX export
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/export.md
  docs/source/imgs/export.png
  examples/pytorch/image_recognition/torchvision_models/export/fx/main.py
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/config.py
  neural_compressor/experimental/export/torch2onnx.py
  neural_compressor/experimental/export/utils.py
  neural_compressor/model/torch_model.py
  neural_compressor/training.py
  test/export/test_torch2onnx.py
Labels: enhancement, extension test

#811 add 3dunet model
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/.dockerignore
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/.gitignore
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/Makefile
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/README.md
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/Task043_BraTS_2019.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/accuracy-brats.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/brats_QSL.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/brats_cal_images_list.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold0_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold1_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold2_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold3_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/folds/fold4_validation.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/mlperf.conf
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/onnxruntime_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/ov_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/preprocess.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/pytorch_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/requirements.txt
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/run.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/run_benchmark.sh
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/run_tuning.sh
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/tf_SUT.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/unet_onnx_to_tf.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/unet_pytorch_to_onnx.py
  examples/pytorch/image_recognition/3d-unet/quantization/ptq/fx/user.conf
Labels: examples, extension test

#899 Enhance MatMul and Gather quantization
  neural_compressor/adaptor/ox_utils/operators/gather.py
  neural_compressor/adaptor/ox_utils/operators/matmul.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
  test/config/test_pythonic_config.py
Labels: enhancement

#917 Adapt Neural Coder for Neural Solution
  neural_coder/backends/keras_inc.yaml
  neural_coder/backends/onnx_inc_dynamic_quant.yaml
  neural_coder/backends/onnx_inc_static_quant_qdq.yaml
  neural_coder/backends/onnx_inc_static_quant_qlinear.yaml
  neural_coder/backends/pytorch_inc_dynamic_quant.yaml
  neural_coder/backends/pytorch_inc_dynamic_quant_fp8.yaml
  neural_coder/backends/pytorch_inc_huggingface_optimum_dynamic.yaml
  neural_coder/backends/pytorch_inc_huggingface_optimum_static.yaml
  neural_coder/backends/pytorch_inc_static_quant_fx.yaml
  neural_coder/backends/pytorch_inc_static_quant_fx_fp8.yaml
  neural_coder/backends/pytorch_inc_static_quant_ipex.yaml
  neural_coder/coders/tensorflow/inc.py
Labels: enhancement

#900 Add weight attribute to SQLinearWrapper class
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix

#916 Enhance the tuning process
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/utils/constant.py
  neural_compressor/strategy/utils/tuning_sampler.py
  neural_compressor/strategy/utils/tuning_space.py
  test/strategy/test_lower_bit_sampler.py
  test/strategy/test_tuning_space_v2.py
Labels: enhancement

#847 Support sq auto tune for ort
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/smooth_quant.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/model/onnx_model.py
  neural_compressor/strategy/strategy.py
  test/algorithm/test_smooth_quant.py
Labels: new feature

#843 Multihead-attention slim enhance
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/run_ffn_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/run_ffn_slim_pipeline.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/run_mha_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_auto_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_no_trainer_auto_slim.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/utils_qa.py
  neural_compressor/compression/callbacks.py
  neural_compressor/compression/pruner/README.md
  neural_compressor/compression/pruner/model_slim/auto_slim.py
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  neural_compressor/compression/pruner/model_slim/weight_slim.py
  neural_compressor/compression/pruner/patterns.py
  neural_compressor/compression/pruner/pruners.py
  neural_compressor/compression/pruner/utils.py
  test/pruning_2.x/test_auto_slim.py
Labels: enhancement

#830 Smooth Quant for Tensorflow backend
  examples/.config/model_params_tensorflow.json
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/README.md
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/run_inference.py
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/run_tuning.sh
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/README.md
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/benchmark.py
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/main.py
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/requirements.txt
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/run_benchmark.sh
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/run_tuning.sh
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tf_utils/graph_util.py
  neural_compressor/adaptor/tf_utils/quantize_graph_common.py
  neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py
  neural_compressor/adaptor/tf_utils/smooth_quant_scaler.py
  neural_compressor/adaptor/tf_utils/util.py
  neural_compressor/experimental/common/model.py
  neural_compressor/model/model.py
  neural_compressor/model/tensorflow_model.py
  neural_compressor/strategy/strategy.py
  neural_compressor/utils/constant.py
  test/adaptor/tensorflow_adaptor/test_smooth_quant_tf.py
  test/itex/test_smooth_quant_itex.py
  test/tfnewapi/test_smooth_quant_newapi.py
Labels: new feature, extension test

#915 Add fp16 ops for onnxrt adaptor
  neural_compressor/adaptor/onnxrt_cuda.yaml
  neural_compressor/adaptor/ox_utils/operators/activation.py
  neural_compressor/adaptor/ox_utils/operators/binary_op.py
  neural_compressor/adaptor/ox_utils/operators/concat.py
  neural_compressor/adaptor/ox_utils/operators/direct_q8.py
  neural_compressor/adaptor/ox_utils/operators/matmul.py
  neural_compressor/adaptor/ox_utils/operators/norm.py
  neural_compressor/adaptor/ox_utils/operators/ops.py
  neural_compressor/adaptor/ox_utils/operators/reduce.py
  neural_compressor/adaptor/ox_utils/operators/split.py
  neural_compressor/adaptor/ox_utils/operators/unary_op.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_operators.py
Labels: enhancement
