Repository intel/neural-compressor, pull requests merged in 2023-06, with the labels that each got.

#931 Fix ITEX Quantize/ Dequantize before BN u8 issue
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
Labels: bug fix

#935 Update tensorflow sq llm example links
  examples/README.md
Labels: documentation

#938 Add missing comma to Neural Insights packages list
  setup.py
Labels: bug fix

#939 support non sq TF LLM
  examples/.config/model_params_tensorflow.json
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/run_tuning.sh
Labels: validation

#927 Update DyNAS-T to 1.3.0
  test/requirements.txt
Labels: enhancement

#933 Update docs add more checks for neural solution
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  .azure-pipelines/scripts/codeScan/pyspelling/pyspelling_conf.yaml
  README.md
  neural_solution/README.md
  neural_solution/docs/source/README.md
  neural_solution/docs/source/description_api.md
  neural_solution/docs/source/get_started.md
  neural_solution/docs/source/imgs/NS-OaaS-Intro.png
  neural_solution/docs/source/template/task_request_description.md
  neural_solution/examples/README.md
  neural_solution/examples/custom_models_optimized/tf_example1/README.md
  neural_solution/examples/custom_models_optimized/tf_example1/task_request_distributed.json
  neural_solution/examples/custom_models_optimized/tf_example1_dis/README.md
  neural_solution/examples/custom_models_optimized/tf_example1_dis/dataset/.gitkeep
  neural_solution/examples/custom_models_optimized/tf_example1_dis/model/.gitkeep
  neural_solution/examples/custom_models_optimized/tf_example1_dis/test.py
  neural_solution/examples/hf_models/README.md
  neural_solution/frontend/fastapi/main_server.py
  neural_solution/frontend/user_facing_api.json
  neural_solution/launcher.py
  neural_solution/requirements.txt
  setup.py
Labels: documentation

#944 Allow dictionary model inputs for onnx export
  neural_compressor/experimental/export/torch2onnx.py
Labels: enhancement

#959 Adjust Pre CI test gap detection range
  .azure-pipelines/scripts/models/generate_report.sh
  .azure-pipelines/scripts/ut/collect_log.sh
Labels: validation

#958 Fixed timeout
  neural_compressor/utils/utility.py
Labels: bug fix

#964 Support mixed precision op name/type dict option
  neural_compressor/config.py
  test/mixed_precision/test_mixed_precision.py
Labels: customer

#921 Update email display to mailto links in markdown files
  README.md
  docs/source/CODE_OF_CONDUCT.md
  docs/source/CONTRIBUTING.md
  docs/source/releases_info.md
Labels: documentation

#924 Refine auto slim code docstrings and readme.
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_no_trainer_auto_slim.py
  neural_compressor/compression/pruner/__init__.py
  neural_compressor/compression/pruner/model_slim/README.md
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  neural_compressor/compression/pruner/model_slim/weight_slim.py
  neural_compressor/compression/pruner/patterns.py
  neural_compressor/compression/pruner/pruners.py
  test/pruning_2.x/test_auto_slim.py
Labels: documentation

#957 Fixed inspect tensor
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/tf_utils/util.py
  neural_compressor/utils/utility.py
  neural_insights/components/diagnosis/diagnosis.py
Labels: bug fix

#951 Fix onnxrt smooth quant
  neural_compressor/adaptor/ox_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix

#982 Bump version of webpack and nth-check for CVE fix
  neural_coder/extensions/neural_compressor_ext_vscode/package.json
  neural_insights/gui/package-lock.json
Labels: bug fix

#966 Enhance model check for LLM
  examples/onnxrt/image_recognition/unet/quantization/ptq_static/requirements.txt
  neural_compressor/model/onnx_model.py
Labels: bug fix

#969 fix fx bf16 op stat issue
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#967 Fix bug in ONNXRT NLP example for onnxruntime1.14.1
  examples/onnxrt/nlp/bert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/bert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/distilbert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/distilbert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/main.py
  examples/onnxrt/nlp/mobilebert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/mobilebert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/gpt2.py
  examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/roberta/quantization/ptq_static/main.py
  neural_compressor/adaptor/ox_utils/operators/gather.py
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/model/onnx_model.py
Labels: bug fix

#989 add pytest to requirements
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/requirements.txt
Labels: bug fix

#993 clean requirements for release packages
  .azure-pipelines/code-scan.yml
  .azure-pipelines/model-test.yml
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
  neural_insights/requirements.txt
  neural_insights/test/components/__init__.py
  neural_insights/test/requirements.txt
  requirements.txt
Labels: enhancement

#943 Add docstring and UTs for Neural Solution
  .azure-pipelines/code-scan-neural-solution.yaml
  .azure-pipelines/docker/DockerfileCodeScan.devel
  .azure-pipelines/scripts/codeScan/bandit/bandit.sh
  .azure-pipelines/scripts/codeScan/pydocstyle/pydocstyle.sh
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path_neural_solution.txt
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  .azure-pipelines/scripts/codeScan/pyspelling/pyspelling.sh
  .azure-pipelines/scripts/codeScan/pyspelling/pyspelling_conf.yaml
  .azure-pipelines/scripts/install_neural_solution.sh
  .azure-pipelines/scripts/ut/run_neural_solution.sh
  .azure-pipelines/template/code-scan-template.yml
  .azure-pipelines/template/docker-template.yml
  .azure-pipelines/ut-neural-solution.yaml
  neural_solution/backend/cluster.py
  neural_solution/backend/result_monitor.py
  neural_solution/backend/runner.py
  neural_solution/backend/scheduler.py
  neural_solution/backend/task.py
  neural_solution/backend/task_db.py
  neural_solution/backend/task_monitor.py
  neural_solution/backend/utils/utility.py
  neural_solution/bin/neural_solution.py
  neural_solution/config.py
  neural_solution/docs/source/README.md
  neural_solution/docs/source/description_api.md
  neural_solution/examples/custom_models_optimized/tf_example1/test.py
  neural_solution/frontend/fastapi/main_server.py
  neural_solution/frontend/gRPC/client.py
  neural_solution/frontend/gRPC/proto/neural_solution_pb2.py
  neural_solution/frontend/gRPC/proto/neural_solution_pb2_grpc.py
  neural_solution/frontend/gRPC/server.py
  neural_solution/frontend/task_submitter.py
  neural_solution/frontend/user_facing_api.json
  neural_solution/frontend/utility.py
  neural_solution/launcher.py
  neural_solution/test/backend/test_runner.py
  neural_solution/test/backend/test_scheduler.py
  neural_solution/test/backend/test_task_monitor.py
  neural_solution/test/test_logger.py
  neural_solution/utils/logger.py
  neural_solution/utils/utility.py
  setup.py
Labels: documentation

#961 Fixed trace issue when input is dictionary
  neural_compressor/adaptor/torch_utils/smooth_quant.py
Labels: bug fix

#991 Fix LLM weight get
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/smooth_quant.py
Labels: bug fix

#997 Fix Crash in inserting Q / DQ around MaxPool for TF Adaptor
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
  neural_compressor/adaptor/tf_utils/graph_util.py
Labels: bug fix

#954 output check added after sq transform
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant.py
  test/algorithm/test_smooth_quant_onnx.py
Labels: enhancement

#995 Fix unet model
  neural_compressor/model/onnx_model.py
Labels: bug fix

#990 Support ipex mixed precision
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
  neural_compressor/adaptor/torch_utils/mixed_precision.py
  neural_compressor/config.py
  neural_compressor/strategy/auto_mixed_precision.py
  neural_compressor/strategy/strategy.py
  test/ipex/test_adaptor_ipex.py
Labels: bug fix

#1000 fix skipconnection bugs when folding=true
  neural_compressor/adaptor/torch_utils/smooth_quant.py
Labels: bug fix

#937 Enable Pruning New API for TF Adaptor
  examples/README.md
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/README.md
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/main.py
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/prepare_model.py
  examples/tensorflow/image_recognition/ViT/pruning/magnitude/requirements.txt
  examples/tensorflow/image_recognition/resnet_v2/pruning/magnitude/README.md
  examples/tensorflow/image_recognition/resnet_v2/pruning/magnitude/main.py
  neural_compressor/adaptor/keras.py
  neural_compressor/compression/callbacks.py
  neural_compressor/compression/pruner/criteria.py
  neural_compressor/compression/pruner/model_slim/auto_slim.py
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  neural_compressor/compression/pruner/patterns.py
  neural_compressor/compression/pruner/pruners.py
  neural_compressor/compression/pruner/utils.py
  neural_compressor/config.py
  neural_compressor/model/model.py
  neural_compressor/training.py
  test/pruning_2.x/test_pruning.py
Labels: new feature

#795 Add doc for developer about how to add new data type
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/add_new_data_type.md
  docs/source/user_guide.md
Labels: documentation

#1003 Improve sq equal check with out_pre_sq and out_post_sq
  neural_compressor/adaptor/torch_utils/smooth_quant.py
Labels: bug fix

#983 Bump transformers version for CVE fix
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/distillation/eager/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/optimization_pipeline/prune_once_for_all/fx/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/distillation/eager/requirements.txt
  examples/pytorch/nlp/huggingface_models/text-classification/optimization_pipeline/prune_once_for_all/fx/requirements.txt
  test/requirements.txt
Labels: bug fix

#1008 remove recover when sq check failed
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  test/algorithm/test_smooth_quant_onnx.py
Labels: bug fix

#996 add code scan CI for neural insights
  .azure-pipelines/code-scan-neural-insights.yaml
  .azure-pipelines/scripts/codeScan/pydocstyle/pydocstyle.sh
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path_neural_insights.txt
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  .azure-pipelines/scripts/codeScan/pyspelling/pyspelling_conf.yaml
  neural_insights/components/diagnosis/diagnosis.py
  neural_insights/components/model/repository.py
  neural_insights/components/workload_manager/quantization_workload.py
  neural_insights/components/workload_manager/workload.py
  neural_insights/components/workload_manager/workload_manager.py
  neural_insights/utils/json_serializer.py
  neural_insights/utils/utils.py
  neural_insights/web/configuration.py
  neural_insights/web/router.py
  neural_insights/web/service/workload.py
Labels: validation

#1016 Auto slim examples: update links
  examples/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_auto_slim_bert-base.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_auto_slim_bert-large.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/run_qa_no_trainer_auto_slim.py
Labels: examples

#1018 Fix Regression of SSD_resnet50 Caused by Maxpooling on ITEX Mode
  neural_compressor/adaptor/tf_utils/graph_rewriter/qdq/insert_qdq_pattern.py
Labels: bug fix

#1024 fix example example_inputs type
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
Labels: bug fix

#1017 Fixed the block detection
  neural_compressor/adaptor/pytorch.py
Labels: bug fix

#1023 Refine dataloader and metric doc
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/dataloader.md
  docs/source/metric.md
Labels: documentation

#1007 Enhance the strategy document
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/tuning_strategies.md
Labels: documentation

#1021 Diagnosis documentation & remove obsolete images
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  docs/source/diagnosis.md
  docs/source/imgs/bench/benchmark-details.png
  docs/source/imgs/bench/benchmark-edit-wizard.png
  docs/source/imgs/bench/benchmarks-table.png
  docs/source/imgs/bench/benchmarks-wizard.png
  docs/source/imgs/bench/custom-dataset.png
  docs/source/imgs/bench/dataset-details.png
  docs/source/imgs/bench/datasets-table.png
  docs/source/imgs/bench/datasets-wizard.png
  docs/source/imgs/bench/diagnosis-actions.png
  docs/source/imgs/bench/diagnosis-model-wise-wizard.png
  docs/source/imgs/bench/diagnosis-tab.jpg
  docs/source/imgs/bench/executed-nas.png
  docs/source/imgs/bench/graph-resnet.jpg
  docs/source/imgs/bench/histogram.jpg
  docs/source/imgs/bench/home.png
  docs/source/imgs/bench/menu.png
  docs/source/imgs/bench/new-nas.png
  docs/source/imgs/bench/optimization-details.png
  docs/source/imgs/bench/optimization-tuning-details.png
  docs/source/imgs/bench/optimizations-table.png
  docs/source/imgs/bench/optimizations-wizard.png
  docs/source/imgs/bench/profiling-details.png
  docs/source/imgs/bench/profiling-edit-wizard.png
  docs/source/imgs/bench/profiling-table.png
  docs/source/imgs/bench/profiling-wizard.png
  docs/source/imgs/bench/project-info.png
  docs/source/imgs/bench/project1.png
  docs/source/imgs/bench/project2.png
  docs/source/imgs/bench/project3-custom.png
  docs/source/imgs/bench/project3-predefined.png
  docs/source/imgs/bench/pruning-details.png
  docs/source/imgs/bench/pruning-wizard.png
  docs/source/imgs/bench/remove1.png
  docs/source/imgs/bench/remove2.png
  docs/source/imgs/bench/see_models.png
  docs/source/imgs/bench/show_graph_button.png
  docs/source/imgs/bench/system_info.png
  docs/source/imgs/bench/system_info_table.png
  docs/source/imgs/bench/wizard2.png
  docs/source/imgs/bench/wizard3.png
  docs/source/imgs/terminal-ops.jpg
  docs/source/imgs/terminal-profiling.jpg
  docs/source/imgs/terminal-weights.jpg
  docs/source/imgs/workflow.jpg
Labels: documentation

#1029 Supported add hook for root module in intermediate layers KD.
  neural_compressor/compression/distillation/criterions.py
  test/distillation/test_distillation_2.x.py
Labels: enhancement

#1013 Refine ORT example dataloader
  docs/source/metric.md
  examples/onnxrt/nlp/bert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/bert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/distilbert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/distilbert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/main.py
  examples/onnxrt/nlp/mobilebert/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/mobilebert/quantization/ptq_static/main.py
  examples/onnxrt/nlp/onnx_model_zoo/gpt2/quantization/ptq_dynamic/gpt2.py
  examples/onnxrt/nlp/roberta/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/roberta/quantization/ptq_static/main.py
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/onnx_evaluation.py
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/smooth_quant.py
  neural_compressor/adaptor/ox_utils/util.py
  neural_compressor/data/dataloaders/dataloader.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: enhancement

#1002 transfer some CI models into 2.x API
  .azure-pipelines/model-test.yml
  .azure-pipelines/scripts/models/env_setup.sh
  .azure-pipelines/scripts/models/run_model_trigger_common.sh
  .azure-pipelines/scripts/models/run_onnxrt_models_trigger.sh
  .azure-pipelines/scripts/models/run_pytorch_models_trigger.sh
  .azure-pipelines/scripts/models/run_tuning_common.sh
  examples/.config/model_params_pytorch.json
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/main.py
  examples/pytorch/image_recognition/torchvision_models/quantization/qat/fx/main.py
Labels: validation

#1030 Fix transformer_lt retval already set issue
  neural_compressor/adaptor/tf_utils/smooth_quant_calibration.py
Labels: bug fix, extension test

#1009 PT supports weight only
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  docs/source/quantization_weight_only.md
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/pytorch_cpu.yaml
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/config.py
  neural_compressor/model/torch_model.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/constant.py
  neural_compressor/strategy/utils/tuning_space.py
  neural_compressor/strategy/utils/utility.py
  neural_compressor/utils/pytorch.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/quantization/test_weight_only_quantization.py
Labels: new feature

#1037 Remove transformers version restriction in ONNXRT token-classification examples
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/data_utils.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/funsd.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_dynamic/trainer.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/data_utils.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/funsd.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmft/quantization/ptq_static/trainer.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/funsd.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/image_utils.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/funsd.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/image_utils.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/install_layoutlmft.sh
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlmv3/quantization/ptq_static/requirements.txt
Labels: examples

#988 PT2ONNX dynamic quantization export
  docs/source/export.md
  examples/.config/model_params_pt2onnx.json
  examples/pytorch/image_recognition/torchvision_models/export/fx/README.md
  examples/pytorch/image_recognition/torchvision_models/export/fx/main.py
  examples/pytorch/image_recognition/torchvision_models/export/fx/run_export.sh
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/README.md
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_export.sh
  examples/pytorch/nlp/huggingface_models/text-classification/export/fx/run_glue.py
  neural_compressor/experimental/export/torch2onnx.py
  neural_compressor/model/torch_model.py
  test/export/test_torch2onnx.py
Labels: new feature
