Repository intel/neural-compressor, pull requests merged in 2023-11, with the labels that each got.

#1358 Fix broken installation + faq links
  README.md
Labels: documentation

#1352 save some resource in signround
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/signround/signround.py
Labels: enhancement

#1380 Introduce INC 3.0 quantization API and port torch RTN into 3.0
  .azure-pipelines/model-test.yml
  .azure-pipelines/scripts/install_nc.sh
  .azure-pipelines/scripts/ut/collect_log_3x.sh
  .azure-pipelines/scripts/ut/coverage.file
  .azure-pipelines/scripts/ut/coverage.pt
  .azure-pipelines/scripts/ut/run_3x_pt.sh
  .azure-pipelines/scripts/ut/run_basic_others.sh
  .azure-pipelines/ut-3x-pt.yml
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
  neural_compressor/common/__init__.py
  neural_compressor/common/base_config.py
  neural_compressor/common/utility.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/algorithms/__init__.py
  neural_compressor/torch/algorithms/rtn_quantize.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils.py
  requirements_pt.txt
  setup.py
  test/3x/torch/test_config.py
Labels: new feature

#1386 [SmoothQuant] make weight_clipping a default_on option
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/tensorflow.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/algorithm/smooth_quant.py
  neural_compressor/strategy/strategy.py
  test/algorithm/test_smooth_quant.py
Labels: enhancement

#1378 add attr to MatMulNBits
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/weight_only.py
Labels: enhancement

#1370 support new IPEX SQ interface design
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_clm.py
  neural_compressor/adaptor/pytorch.py
Labels: enhancement

#1384 Refinement of sparseGPT results.
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_sparsegpt.py
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/scripts/run_llm_sparsegpt.sh
  neural_compressor/compression/pruner/pruning.py
  neural_compressor/compression/pruner/utils.py
Labels: bug fix

#1379 add use_HF_format for export_compressed_model
  docs/source/quantization_weight_only.md
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  neural_compressor/model/torch_model.py
  neural_compressor/utils/load_huggingface.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor.py
  test/model/test_model_pytorch.py
Labels: enhancement

#1397 Enhance 3.x API
  .azure-pipelines/scripts/ut/run_3x_pt.sh
  .azure-pipelines/ut-3x-pt.yml
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
  neural_compressor/common/__init__.py
  neural_compressor/common/base_config.py
  neural_compressor/common/logger.py
  neural_compressor/common/utility.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/algorithms/rtn.py
  neural_compressor/torch/algorithms/rtn_quantize.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils.py
  test/3x/torch/test_config.py
  test/3x/torch/test_logger.py
  test/3x/torch/test_rtn.py
  test/3x/torch/test_utils.py
Labels: INC3.X

#1389 Support ONNXRT layer-wise W8A8 quantization
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/model/onnx_model.py
  test/adaptor/onnxrt_adaptor/test_layer_wise.py
  test/model/test_onnx_model.py
Labels: new feature

#1405 support for restoring ipex model from json
  neural_compressor/utils/pytorch.py
  test/algorithm/test_smooth_quant.py
Labels: new feature

#1348 support xpu device
  examples/pytorch/image_recognition/torchvision_models/quantization/ptq/cpu/ipex/main.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/quantization/ptq_static/ipex/run_quant.sh
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/pytorch_ipex.yaml
  neural_compressor/adaptor/torch_utils/mixed_precision.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/compression/distillation/criterions.py
  neural_compressor/config.py
  neural_compressor/experimental/common/criterion.py
  neural_compressor/experimental/nas/basic_nas.py
  neural_compressor/strategy/auto_mixed_precision.py
  test/ipex/test_adaptor_ipex.py
Labels: new feature, WIP

#1404 Add ITREX unit test
  .azure-pipelines/scripts/ut/run_itrex.sh
  .azure-pipelines/ut-itrex.yml
Labels: validation

#1403 Support dml quantization and add example
  docs/source/quantization.md
  examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/README.md
  examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/main.py
  examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/image_recognition/onnx_model_zoo/shufflenet/quantization/ptq_static/run_quant.sh
  neural_compressor/adaptor/onnxrt.py
Labels: enhancement, examples

#1398 fix python script typos in smooth_quant.md
  docs/source/smooth_quant.md
Labels: documentation

#1345 Add an ONNXRT WOQ tuning example
  docs/source/quantization_weight_only.md
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/run_quant.sh
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/weight_only.py
  neural_compressor/model/onnx_model.py
  neural_compressor/strategy/strategy.py
  test/adaptor/onnxrt_adaptor/test_weight_only_adaptor.py
Labels: examples, extension test

#1399 increase sq auto alpha running speed
  neural_compressor/adaptor/torch_utils/smooth_quant.py
Labels: enhancement

#1408 Port torch GPTQ to 3.x
  .azure-pipelines/scripts/ut/run_itrex.sh
  neural_compressor/common/base_config.py
  neural_compressor/common/utility.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/algorithms/__init__.py
  neural_compressor/torch/algorithms/gptq.py
  neural_compressor/torch/algorithms/rtn.py
  neural_compressor/torch/algorithms/rtn_quantize.py
  neural_compressor/torch/algorithms/weight_only_algos.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils.py
  test/3x/torch/test_config.py
  test/3x/torch/test_gptq_algo.py
Labels: INC3.X

#1423 Fix model preparation step failure in ONNXRT examples
  examples/onnxrt/image_recognition/resnet50_mlperf/quantization/ptq_static/README.md
  examples/onnxrt/image_recognition/resnet50_mlperf/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/ssd_mobilenet_v1/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/ssd_mobilenet_v2/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/ssd_mobilenet_v2/quantization/ptq_static/prepare_model.py
Labels: bug fix

#1418 enhance onnx data format check
  neural_compressor/adaptor/ox_utils/util.py
Labels: bug fix
