Repository intel/neural-compressor, pull requests merged in 2023-10, with the labels that each got.

#1305 Add example of PyTorch model tensor dump with Neural Insights
  neural_insights/README.md
  neural_insights/docs/source/pytorch_nlp_cli_mode.md
Labels: documentation

#1272 CI FWs version update
  .azure-pipelines/docker/Dockerfile.devel
  .azure-pipelines/docker/DockerfileCodeScan.devel
  .azure-pipelines/docker/DockerfileWithNC.devel
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  .azure-pipelines/scripts/models/env_setup.sh
  .azure-pipelines/scripts/models/run_onnxrt_models_trigger.sh
  .azure-pipelines/scripts/models/run_pytorch_models_trigger.sh
  .azure-pipelines/scripts/models/run_tensorflow_models_trigger.sh
  .azure-pipelines/scripts/ut/env_setup.sh
  .azure-pipelines/scripts/ut/ut_fwk_version.sh
  docs/source/installation_guide.md
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/post_quantized_op_cse.py
  neural_compressor/data/datasets/dataset.py
  neural_compressor/experimental/data/datasets/dataset.py
  neural_compressor/experimental/strategy/bayesian.py
Labels: validation

#1309 support Coverity scan with oneCICD repo
  .github/workflows/Scanner_Bdba.yml
  .github/workflows/Scanner_Coverity.yml
  .github/workflows/Scanner_McAfee.yml
Labels: validation

#1312 Update benchmark part in ONNXRT quick started notebook
  examples/notebook/onnxruntime/Quick_Started_Notebook_of_INC_for_ONNXRuntime.ipynb
  examples/notebook/onnxruntime/benchmark.py
Labels: bug fix

#1315 fix tensorflow example scripts typo
  examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/run_quant.sh
  examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/run_quant.sh
  examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/run_quant.sh
Labels: bug fix

#1325 update CONTRIBUTING.md
  docs/source/CONTRIBUTING.md
Labels: documentation

#1314 Add table-transformer-detection ONNXRT example
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/README.md
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/export.sh
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/patch
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/prepare_model.py
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/object_detection/table_transformer/quantization/ptq_static/run_quant.sh
Labels: examples

#1277 Update gptj example with the newest GPTQ API.
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_gptj_mlperf_int4.py
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_weight_only/run_gptj_mlperf_int4.sh
  neural_compressor/adaptor/torch_utils/gptq.py
Labels: examples

#1333 Update ITREX version in ONNXRT WOQ example and fix bugs in hf models
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
Labels: bug fix

#1328 Enable the tuning of WOQ algorithm
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/strategy/auto.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/strategy.py
  neural_compressor/strategy/utils/constant.py
  neural_compressor/strategy/utils/tuning_sampler.py
  neural_compressor/utils/utility.py
  test/adaptor/onnxrt_adaptor/test_weight_only_adaptor.py
Labels: new feature

#1300 add notebook example for pytorch
  examples/README.md
  examples/notebook/pytorch/Quick_Started_Notebook_of_INC_for_Pytorch.ipynb
  examples/notebook/pytorch/benchmark.py
Labels: examples

#1336 refine release binary build for 3.0 API
  setup.cfg
  setup.py
Labels: new feature

#1351 freeze ruamel_yaml version for CI test
  .azure-pipelines/scripts/models/env_setup.sh
Labels: bug fix

#1322 Add BEiT ONNXRT example
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/README.md
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/beit_modeling_finetune.py
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/main.py
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/prepare_model.py
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/requirements.txt
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/image_recognition/beit/quantization/ptq_static/run_quant.sh
Labels: examples

#1356 docs/source/NAS.md
  docs/source/NAS.md
Labels: documentation
