Repository intel/neural-compressor, pull requests merged in 2023-04, with the labels that each got.

#753 Fix Keras model mix precision convert issue
  neural_compressor/mix_precision.py
  test/mixed_precision/test_mixed_precision_keras_model.py
Labels: bug fix

#632 Enable automatic model slim for channel pruning and MHA pruning.
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/ffn_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/ffn_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/ffn_slim/run_ffn_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/ffn_slim/run_ffn_slim_pipeline.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/ffn_slim/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/ffn_slim/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/run_mha_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/run_mha_slim_pipeline.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/run_qa.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/mha_slim/utils_qa.py
  neural_compressor/compression/__init__.py
  neural_compressor/compression/callbacks.py
  neural_compressor/compression/pruner/model_slim/__init__.py
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  neural_compressor/compression/pruner/model_slim/weight_slim.py
  neural_compressor/compression/pruner/pruners.py
  neural_compressor/compression/pruner/utils.py
  neural_compressor/training.py
  test/pruning_2.x/test_auto_slim.py
Labels: new feature

#782 update alpha distribution of auto tuning smoothquant
  docs/source/smooth_quant.md
Labels: documentation

#780 Enhance mse_v2 strategy
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/strategy/mse_v2.py
  neural_compressor/strategy/utils/constant.py
  neural_compressor/strategy/utils/tuning_structs.py
Labels: enhancement

#777 Fixed the wrong description
  neural_compressor/quantization.py
  neural_compressor/training.py
Labels: documentation

#783 add gptj alpha-tuning example and fix md typo
  docs/source/smooth_quant.md
  examples/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py
Labels: documentation, examples

#708 ORT calibration algorithm support Entropy/KL & Percentile
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/onnxrt.yaml
  neural_compressor/adaptor/onnxrt_cuda.yaml
  neural_compressor/adaptor/onnxrt_trt.yaml
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/calibrator.py
  neural_compressor/conf/config.py
  neural_compressor/config.py
  neural_compressor/model/onnx_model.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_augment.py
Labels: new feature

#787 update example and readme
  .azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt
  README.md
  docs/source/publication_list.md
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/run_benchmark.sh
  examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/main.py
Labels: examples

#775 add block_mask & retrain_free features
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_llm_pruning.sh
  examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer_block.py
  neural_compressor/compression/pruner/criteria.py
  neural_compressor/compression/pruner/patterns.py
  neural_compressor/compression/pruner/pruners.py
  neural_compressor/compression/pruner/utils.py
  test/pruning_2.x/test_pruning_block.py
  test/pruning_2_plus.x/test_pruning_block.py
Labels: new feature

#793 add peleenet to pytorch examples
  examples/.config/model_params_pytorch.json
  examples/README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/LICENSE
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/PeleeNet_README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/README.md
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/main.py
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/peleenet.py
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/requirements.txt
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_benchmark.sh
  examples/pytorch/image_recognition/peleenet/quantization/ptq/fx/run_tuning.sh
Labels: examples, extension test

#800 Fix ITEX OOB100 FBN regression issue
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/freeze_value.py
Labels: bug fix

#804 update pre-ci ut-coverage docker config
  .azure-pipelines/ut-basic.yml
Labels: validation

#799 update SmoothQuant algorithm with folding choice
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/ipex/smooth_quant/eval_lambada.py
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/algorithm/smooth_quant.py
  neural_compressor/config.py
  neural_compressor/strategy/strategy.py
  test/algorithm/test_smooth_quant.py
Labels: new feature

#794 Support KerasModel just on Keras backend
  neural_compressor/mix_precision.py
  neural_compressor/model/model.py
Labels: bug fix, extension test

#704 ONNXRT block fallback for nlp model quantization
  examples/.config/model_params_onnxrt.json
  examples/README.md
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/export.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/export.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/language_modeling/quantization/ptq_static/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/question_answering/quantization/ptq_static/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/run_tuning.sh
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  neural_compressor/adaptor/ox_utils/calibrator.py
  neural_compressor/config.py
  neural_compressor/model/onnx_model.py
  neural_compressor/strategy/basic.py
  neural_compressor/strategy/utils/tuning_sampler.py
Labels: new feature

#789 Auto slim enhance
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/run_ffn_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/run_ffn_slim_pipeline.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/feed_forward_network_slim/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/README.md
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/requirements.txt
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/run_mha_slim.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/run_mha_slim_pipeline.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/run_qa.sh
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/timers.py
  examples/pytorch/nlp/huggingface_models/question-answering/model_slim/multi_heads_attention_slim/utils_qa.py
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer.py
  examples/pytorch/nlp/huggingface_models/text-classification/pruning/eager/run_glue_no_trainer.py
  neural_compressor/compression/callbacks.py
  neural_compressor/compression/pruner/README.md
  neural_compressor/compression/pruner/model_slim/README.md
  neural_compressor/compression/pruner/model_slim/auto_slim.py
  neural_compressor/compression/pruner/model_slim/imgs/auto_slim_feed_forward_network.png
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  neural_compressor/compression/pruner/model_slim/weight_slim.py
  neural_compressor/compression/pruner/pruners.py
  neural_compressor/compression/pruner/utils.py
  test/pruning_2.x/test_auto_slim.py
Labels: enhancement

#724 Add GPTJ-6B onnx model example
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_dynamic/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_dynamic/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_dynamic/run_tuning.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_static/run_benchmark.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/quantization/ptq_static/run_tuning.sh
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/model/onnx_model.py
Labels: examples

#798 Fix the Distillation Example of TF Backend
  examples/tensorflow/image_recognition/tensorflow_models/distillation/README.md
  examples/tensorflow/image_recognition/tensorflow_models/distillation/main.py
  neural_compressor/compression/callbacks.py
  neural_compressor/compression/pruner/model_slim/pattern_analyzer.py
  neural_compressor/compression/pruner/model_slim/weight_slim.py
  neural_compressor/experimental/compression/pruning.py
  neural_compressor/model/model.py
Labels: examples, extension test

#764 Add operators statistics for IPEX backend
  neural_compressor/adaptor/pytorch.py
Labels: enhancement

#805 pruning/sq doc update
  docs/source/pruning.md
  docs/source/smooth_quant.md
  neural_compressor/compression/pruner/README.md
Labels: documentation

#801 whisper large evaluation code
  examples/.config/model_params_pytorch.json
  examples/pytorch/speech_recognition/whisper_large/quantization/ptq_dynamic/fx/README.md
  examples/pytorch/speech_recognition/whisper_large/quantization/ptq_dynamic/fx/requirements.txt
  examples/pytorch/speech_recognition/whisper_large/quantization/ptq_dynamic/fx/run_benchmark.sh
  examples/pytorch/speech_recognition/whisper_large/quantization/ptq_dynamic/fx/run_tuning.sh
  examples/pytorch/speech_recognition/whisper_large/quantization/ptq_dynamic/fx/run_whisper_large.py
Labels: examples

#826 Update DyNAS-T to 1.2
  test/requirements.txt
Labels: bug fix

#841 Update ITEX GPU Information for TF Examples
  docs/source/mixed_precision.md
  docs/source/quantization.md
  examples/tensorflow/image_recognition/SavedModel/efficientnet_v2_b0/quantization/ptq/README.md
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/distillation/README.md
  examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_resnet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/inception_v4/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v3/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_101/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_152/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_50/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/quantization/ptq/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vgg19/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_inception_resnet_v2/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet101/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/mask_rcnn_inception_v2/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet34/quantization/ptq/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_resnet50_v1/quantization/ptq/README.md
  examples/tensorflow/object_detection/yolo_v3/quantization/ptq/README.md
  examples/tensorflow/style_transfer/arbitrary_style_transfer/quantization/ptq/README.md
Labels: documentation

#838 Fix ONNXRT mask_rcnn quantize failed
  neural_compressor/adaptor/ox_utils/calibration.py
Labels: bug fix, extension test

#822 Fix OOB DynamicMemory model quantize issue
  neural_compressor/adaptor/tf_utils/graph_util.py
Labels: bug fix, examples, extension test

#824 fix clm examples regression
  examples/pytorch/nlp/huggingface_models/language-modeling/quantization/ptq_static/fx/run_clm.py
Labels: bug fix, examples, extension test

#802 Remove device-specific information from the node to ensure compatibility with different devices
  neural_compressor/adaptor/tf_utils/graph_rewriter/generic/pre_optimize.py
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/post_hostconst_converter.py
  neural_compressor/model/tensorflow_model.py
Labels: bug fix

#796 Support BMM dequantize output bf16
  neural_compressor/adaptor/tf_utils/graph_rewriter/int8/fuse_matmul_redundant_dequantize.py
Labels: examples, extension test

#790 Support profiling for TF distilbert_base model
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/run_benchmark.sh
  examples/tensorflow/nlp/distilbert_base/quantization/ptq/run_inference.py
Labels: examples, extension test

#844 Fix TF image recognition benchmark accuracy evaluate issue
  examples/helloworld/tf_example6/test.py
  examples/keras/image_recognition/inception_resnet_v2/quantization/ptq/main.py
  examples/keras/image_recognition/inception_v3/quantization/ptq/main.py
  examples/keras/image_recognition/mobilenet_v2/quantization/ptq/main.py
  examples/keras/image_recognition/resnet101/quantization/ptq/main.py
  examples/keras/image_recognition/resnet50/quantization/ptq/main.py
  examples/keras/image_recognition/resnet50_fashion/quantization/ptq/main.py
  examples/keras/image_recognition/resnetv2_101/quantization/ptq/main.py
  examples/keras/image_recognition/resnetv2_50/quantization/ptq/main.py
  examples/keras/image_recognition/vgg16/quantization/ptq/main.py
  examples/keras/image_recognition/vgg19/quantization/ptq/main.py
  examples/keras/image_recognition/xception/quantization/ptq/main.py
  examples/tensorflow/image_recognition/SavedModel/efficientnet_v2_b0/quantization/ptq/main.py
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/SavedModel/mobilenet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/resnet_v2/quantization/qat/main.py
  examples/tensorflow/image_recognition/tensorflow_models/densenet121/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/densenet161/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/densenet169/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/efficientnet-b0/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_resnet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v3/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/inception_v4/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v3/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1_5/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_101/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_152/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet_v2_50/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/quantization/ptq/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg19/quantization/ptq/main.py
  neural_compressor/benchmark.py
Labels: bug fix, extension test
