Repository intel/neural-compressor, pull requests merged in 2024-05, with the labels that each got.

#1765 Migrate RTN, HQQ and AWQ to Torch new 3.x API
  neural_compressor/torch/algorithms/base_algorithm.py
  neural_compressor/torch/algorithms/static_quant/static_quant.py
  neural_compressor/torch/algorithms/weight_only/awq.py
  neural_compressor/torch/algorithms/weight_only/hqq/__init__.py
  neural_compressor/torch/algorithms/weight_only/hqq/quant_api.py
  neural_compressor/torch/algorithms/weight_only/hqq/quantizer.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/algorithm_entry.py
  test/3x/torch/quantization/weight_only/hqq/test_hqq_cpu.py
  test/3x/torch/quantization/weight_only/hqq/test_hqq_cuda.py
  test/3x/torch/quantization/weight_only/test_awq.py
  test/3x/torch/quantization/weight_only/test_rtn.py
Labels: INC3.X, PyTorch

#1774 Update the coding style doc
  docs/source/coding_style.md
Labels: documentation

#1780 Remove TF2ONNX Examples
  examples/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/README.md
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/run_benchmark.sh
  examples/tensorflow/image_recognition/tensorflow_models/mobilenet_v2/export/run_export.sh
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/README.md
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/run_benchmark.sh
  examples/tensorflow/image_recognition/tensorflow_models/resnet50_v1/export/run_export.sh
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/README.md
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/main.py
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/requirements.txt
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/run_benchmark.sh
  examples/tensorflow/image_recognition/tensorflow_models/vgg16/export/run_export.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/README.md
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/main.py
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/faster_rcnn_resnet50/export/run_export.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/README.md
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/main.py
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/requirements.txt
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/run_benchmark.sh
  examples/tensorflow/object_detection/tensorflow_models/ssd_mobilenet_v1/export/run_export.sh
Labels: TensorFlow

#1779 Enhance 3.x torch algorithm entry
  neural_compressor/torch/algorithms/base_algorithm.py
  neural_compressor/torch/algorithms/weight_only/autoround.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils/utility.py
  test/3x/torch/quantization/weight_only/test_autoround.py
  test/3x/torch/quantization/weight_only/test_mixed_algos.py
Labels: INC3.X, PyTorch

#1782 Add torch WOQ tuning
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  test/3x/torch/test_autotune.py
Labels: PyTorch

#1787 Enhance 3.x torch UT
  test/3x/torch/quantization/test_static_quant.py
  test/3x/torch/quantization/weight_only/hqq/test_hqq_cpu.py
  test/3x/torch/quantization/weight_only/hqq/test_hqq_cuda.py
  test/3x/torch/quantization/weight_only/test_autoround.py
  test/3x/torch/quantization/weight_only/test_awq.py
  test/3x/torch/quantization/weight_only/test_gptq.py
  test/3x/torch/quantization/weight_only/test_rtn.py
  test/3x/torch/quantization/weight_only/test_teq.py
Labels: INC3.X, PyTorch

#1795 Add pt2e dynamic quantization
  neural_compressor/torch/algorithms/pt2e_quant/__init__.py
  neural_compressor/torch/algorithms/pt2e_quant/core.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/utils/constants.py
  neural_compressor/torch/utils/environ.py
  neural_compressor/torch/utils/utility.py
  test/3x/torch/algorithms/pt2e_quant/test_pt2e_w8a8.py
  test/3x/torch/quantization/test_pt2e_quant.py
Labels: INC3.X

#1781 Detect the number of sockets when needed
  neural_compressor/utils/utility.py
  test/utils/test_cpu_info.py
Labels: bug fix, 2.x

#1793 Support Autotune FP16 Mix-precision on torch 3.0 new API
  neural_compressor/common/utils/constants.py
  neural_compressor/torch/algorithms/mix_precision/__init__.py
  neural_compressor/torch/algorithms/mix_precision/half_precision_convert.py
  neural_compressor/torch/algorithms/mix_precision/module_wrappers.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  test/3x/torch/test_autotune.py
Labels: INC3.X, PyTorch

#1728 add mx quant
  docs/source/imgs/mx_workflow.png
  docs/source/mx_quantization.md
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/mx/README.md
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/mx/requirements.txt
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/mx/run_clm_no_trainer.py
  neural_compressor/common/utils/constants.py
  neural_compressor/torch/algorithms/mx_quant/__init__.py
  neural_compressor/torch/algorithms/mx_quant/mx.py
  neural_compressor/torch/algorithms/mx_quant/utils.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  test/3x/torch/quantization/test_mx_quant.py
Labels: new feature

#1798 Support mixed `INT8` + `FP16` in one model
  neural_compressor/torch/algorithms/pt2e_quant/core.py
  neural_compressor/torch/algorithms/pt2e_quant/half_precision_rewriter.py
  neural_compressor/torch/utils/utility.py
  test/3x/torch/algorithms/pt2e_quant/test_half_precision_rewriter.py
  test/3x/torch/quantization/test_pt2e_quant.py
  test/3x/torch/requirements.txt
Labels: INC3.X, PyTorch, PT2E

#1804 Enhance GPTQ `act_order` UT
  test/3x/torch/quantization/weight_only/test_gptq.py
Labels: INC3.X

#1813 Update lm-eval evaluate in ort llm example
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
  neural_compressor/adaptor/ox_utils/weight_only.py
Labels: examples, ONNX Runtime

#1818 Fix TF 2x LLM SQ Legacy Keras Environment Variable Issue
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/benchmark.py
  examples/tensorflow/nlp/large_language_models/quantization/ptq/smoothquant/main.py
Labels: bug fix, TensorFlow, 2.x

#1810 Support `auto_round` integration 3.x
  .azure-pipelines/scripts/ut/env_setup.sh
  neural_compressor/torch/algorithms/weight_only/autoround.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/utils/environ.py
  test/3x/torch/quantization/weight_only/test_autoround.py
Labels: INC3.X, PyTorch
