Repository intel/neural-compressor, pull requests merged in 2024-06, with the labels that each got.

#1825 Add doc for autotune
  docs/3x/autotune.md
Labels: documentation, Auto-Tune

#1840 Fix `dtype` of `unpacked tensor`
  neural_compressor/torch/algorithms/weight_only/modules.py
Labels: INC3.X, PyTorch

#1843 Remove Depracated TF2ONNX UT Case
  test/itex/test_tensorflow_qdq_convert_to_onnx_qdq.py
Labels: bug fix, TensorFlow, 2.x

#1841 Add INC 3 workflow diagram
  docs/3x/imgs/INC3_WORKFLOW.png
Labels: documentation

#1848 Add fallback support for HQQ
  neural_compressor/torch/algorithms/weight_only/hqq/quantizer.py
  neural_compressor/torch/quantization/config.py
  test/3x/torch/quantization/weight_only/hqq/test_hqq_cpu.py
Labels: INC3.X

#1850 Improve UT coverage for WOQ
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
  neural_compressor/torch/algorithms/weight_only/awq.py
  neural_compressor/torch/algorithms/weight_only/gptq.py
  neural_compressor/torch/algorithms/weight_only/modules.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
  neural_compressor/torch/algorithms/weight_only/save_load.py
  neural_compressor/torch/algorithms/weight_only/teq.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/algorithm_entry.py
  test/3x/torch/quantization/weight_only/hqq/test_packer.py
  test/3x/torch/quantization/weight_only/test_awq.py
  test/3x/torch/quantization/weight_only/test_rtn.py
  test/3x/torch/quantization/weight_only/test_woq_on_cuda.py
  test/3x/torch/quantization/weight_only/test_woq_utils.py
  test/3x/torch/test_autotune.py
Labels: INC3.X, PyTorch

#1861 Fix config expansion with empty options
  neural_compressor/common/base_config.py
  test/3x/common/test_common.py
Labels: INC3.X

#1849 Add 3x architecture diagram
  docs/3x/imgs/architecture.png
Labels: documentation

#1826 Enhance INC WOQ model loading & support Huggingface WOQ model loading
  docs/3x/PT_WeightOnlyQuant.md
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/habana_fp8/run_llm.py
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
  neural_compressor/torch/algorithms/weight_only/__init__.py
  neural_compressor/torch/algorithms/weight_only/save_load.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/load_entry.py
  neural_compressor/torch/utils/constants.py
  test/3x/torch/algorithms/weight_only/test_woq_utility.py
  test/3x/torch/quantization/weight_only/test_autoround.py
  test/3x/torch/quantization/weight_only/test_awq.py
  test/3x/torch/quantization/weight_only/test_gptq.py
  test/3x/torch/quantization/weight_only/test_load_woq_hf_model.py
  test/3x/torch/quantization/weight_only/test_rtn.py
  test/3x/torch/quantization/weight_only/test_teq.py
Labels: INC3.X, PyTorch

#1853 Add PT2E cv&llm example
  docs/3x/PT_StaticQuant.md
  examples/.config/model_params_pytorch_3x.json
  examples/3.x_api/pytorch/cv/static_quant/README.md
  examples/3.x_api/pytorch/cv/static_quant/extract_ILSVRC.sh
  examples/3.x_api/pytorch/cv/static_quant/main.py
  examples/3.x_api/pytorch/cv/static_quant/requirements.txt
  examples/3.x_api/pytorch/cv/static_quant/run_quant.sh
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/README.md
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/requirements.txt
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/run_clm_no_trainer.py
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/run_quant.sh
Labels: examples, INC3.X

#1873 Fix GPTQ layers match
  neural_compressor/torch/algorithms/weight_only/gptq.py
Labels: PyTorch

#1876 Add op statistics dump for woq
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/utils/utility.py
  requirements_pt.txt
Labels: PyTorch
