Repository intel/neural-compressor, pull requests merged in 2024-02, with the labels that each got.

#1592 Add more algo names in advance
  neural_compressor/common/utils/constants.py
Labels: INC3.X, module: common

#1591 Support double quant tuning
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/quantization/quantize.py
  test/3x/torch/test_autotune.py
Labels: Auto-Tune, PyTorch

#1595 Refine base config for 3.x
  neural_compressor/common/base_config.py
  neural_compressor/onnxrt/quantization/config.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
Labels: INC3.X

#1561 PyTorch AWQ Weight-only 3x API Implementation
  neural_compressor/torch/__init__.py
  neural_compressor/torch/algorithms/__init__.py
  neural_compressor/torch/algorithms/habana_fp8/__init__.py
  neural_compressor/torch/algorithms/habana_fp8/fp8_quant.py
  neural_compressor/torch/algorithms/habana_fp8/modules.py
  neural_compressor/torch/algorithms/habana_fp8/observer.py
  neural_compressor/torch/algorithms/weight_only/__init__.py
  neural_compressor/torch/algorithms/weight_only/awq.py
  neural_compressor/torch/algorithms/weight_only/gptq.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/amp/__init__.py
  neural_compressor/torch/amp/autocast.py
  neural_compressor/torch/amp/fp8/__init__.py
  neural_compressor/torch/amp/fp8/functions.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/modules.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils/__init__.py
  neural_compressor/torch/utils/constants.py
  neural_compressor/torch/utils/utility.py
  test/3x/torch/quantization/weight_only/test_awq.py
  test/3x/torch/test_config.py
Labels: INC3.X, PyTorch

#1584 Add coding style docs and recommended VS Code setting
  .pre-commit-config.yaml
  .vscode/settings_recommended.json
  docs/source/CONTRIBUTING.md
  docs/source/coding_style.md
Labels: documentation

#1596 Migrate static quant ipex backend to 3.x API
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/torch/algorithms/static_quant/__init__.py
  neural_compressor/torch/algorithms/static_quant/static_quant.py
  neural_compressor/torch/algorithms/static_quant/utility.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils/environ.py
  neural_compressor/utils/pytorch.py
  requirements_pt.txt
  test/3x/torch/quantization/test_static_quant.py
  test/3x/torch/requirements.txt
Labels: INC3.X, PyTorch

#1608 Enhance auto-tune module
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  neural_compressor/common/__init__.py
  neural_compressor/common/base_config.py
  neural_compressor/common/base_tuning.py
  neural_compressor/common/tuning_param.py
  neural_compressor/common/utils/utility.py
  neural_compressor/torch/quantization/autotune.py
  requirements_ort.txt
  requirements_pt.txt
  requirements_tf.txt
  test/3x/common/test_common.py
  test/3x/common/test_param.py
  test/3x/onnxrt/test_autotune.py
  test/3x/onnxrt/test_config.py
  test/3x/tensorflow/keras/test_config.py
Labels: INC3.X, Auto-Tune

#1578 ONNXRT LLM examples support latest optimum version
  examples/.config/model_params_onnxrt.json
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/run_quant.sh
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/README.md
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/run_benchmark.sh
  neural_compressor/model/onnx_model.py
Labels: examples

#1598 PyTorch TEQ Weight-only 3x API Implementation
  neural_compressor/torch/algorithms/weight_only/__init__.py
  neural_compressor/torch/algorithms/weight_only/teq.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/utils/constants.py
  test/3x/torch/quantization/weight_only/test_rtn.py
  test/3x/torch/quantization/weight_only/test_teq.py
  test/3x/torch/test_config.py
Labels: INC3.X, PyTorch

#1615 Add unified log to the quantization process
  neural_compressor/common/__init__.py
  neural_compressor/common/base_tuning.py
  neural_compressor/common/utils/__init__.py
  neural_compressor/common/utils/logger.py
  neural_compressor/common/utils/utility.py
  neural_compressor/onnxrt/quantization/quantize.py
  neural_compressor/tensorflow/quantization/quantize.py
  neural_compressor/torch/quantization/quantize.py
Labels: module: common

#1611 Fix GPTQ/RTN 3.x example & fix asym quantize
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/README.md
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/requirements.txt
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_clm_no_trainer.py
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/run_quant.sh
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/llm/utils.py
  neural_compressor/torch/utils/utility.py
Labels: INC3.X, PyTorch

#1616 Enable the Combination of Multiple Algorithms within a Single Model
  neural_compressor/common/base_config.py
  neural_compressor/torch/quantization/algorithm_entry.py
  test/3x/common/test_common.py
  test/3x/torch/quantization/weight_only/test_mixed_algos.py
Labels: INC3.X, PyTorch

#1496 WAQ refactor[WIP]
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  docs/source/smooth_quant.md
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/awq.py
  neural_compressor/adaptor/torch_utils/layer_wise_quant/quantize.py
  neural_compressor/adaptor/torch_utils/model_wrapper.py
  neural_compressor/adaptor/torch_utils/smooth_quant.py
  neural_compressor/adaptor/torch_utils/teq.py
  neural_compressor/adaptor/torch_utils/util.py
  neural_compressor/adaptor/torch_utils/waq/README.md
  neural_compressor/adaptor/torch_utils/waq/__init__.py
  neural_compressor/adaptor/torch_utils/waq/auto_alpha.py
  neural_compressor/adaptor/torch_utils/waq/calibration.py
  neural_compressor/adaptor/torch_utils/waq/graph_trace.py
  neural_compressor/adaptor/torch_utils/waq/smooth_quant.py
  neural_compressor/adaptor/torch_utils/waq/utils.py
  test/algorithm/test_smooth_quant.py
  test/quantization/test_weight_only_quantization.py
Labels: draft

#1631 Fixed smooth quant's UTs
  test/algorithm/test_smooth_quant.py
Labels: bug fix

#1627 Fix Neural Solution SQL/CMD injection
  neural_solution/backend/scheduler.py
  neural_solution/examples/custom_models_optimized/tf_example1/README.md
  neural_solution/examples/custom_models_optimized/tf_example1/task_request.json
  neural_solution/examples/custom_models_optimized/tf_example1/task_request_distributed.json
  neural_solution/examples/hf_models/README.md
  neural_solution/examples/hf_models/task_request.json
  neural_solution/examples/hf_models_grpc/README.md
  neural_solution/examples/hf_models_grpc/task_request.json
  neural_solution/frontend/fastapi/main_server.py
  neural_solution/frontend/utility.py
  neural_solution/test/frontend/fastapi/test_main_server.py
  neural_solution/test/frontend/fastapi/test_utils.py
Labels: security

#1625 Enable LWQ for onnxrt WOQ in 3.x API
  neural_compressor/onnxrt/algorithms/__init__.py
  neural_compressor/onnxrt/algorithms/layer_wise/__init__.py
  neural_compressor/onnxrt/algorithms/layer_wise/core.py
  neural_compressor/onnxrt/algorithms/weight_only/awq.py
  neural_compressor/onnxrt/algorithms/weight_only/gptq.py
  neural_compressor/onnxrt/algorithms/weight_only/rtn.py
  neural_compressor/onnxrt/algorithms/weight_only/utility.py
  neural_compressor/onnxrt/quantization/config.py
  neural_compressor/onnxrt/utils/onnx_model.py
  neural_compressor/onnxrt/utils/utility.py
  test/3x/onnxrt/quantization/layer_wise/test_layer_wise.py
  test/3x/onnxrt/requirements.txt
Labels: INC3.X, ONNX Runtime

#1634 Support auto device for TEQ and AWQ
  neural_compressor/torch/algorithms/weight_only/awq.py
  neural_compressor/torch/algorithms/weight_only/teq.py
  neural_compressor/torch/utils/auto_accelerator.py
  test/3x/torch/quantization/weight_only/test_woq_on_cuda.py
Labels: INC3.X, PyTorch
