Repository intel/neural-compressor, pull requests merged in 2024-01, with the labels that each got.

#1510 Add regular expression matching for base config
  neural_compressor/common/base_config.py
  test/3x/torch/test_config.py
Labels: INC3.X

#1512 Enhance the ORT node name checking
  neural_compressor/adaptor/ox_utils/quantizer.py
  neural_compressor/adaptor/ox_utils/util.py
  test/adaptor/onnxrt_adaptor/test_adaptor_onnxrt.py
Labels: bug fix

#1497 Introduce INC3.0 auto-tune
  neural_compressor/common/base_config.py
  neural_compressor/common/base_tune.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/tune.py
  test/3x/tensorflow/test_config.py
  test/3x/torch/test_autotune.py
  test/3x/torch/test_config.py
Labels: INC3.X

#1517 [ILITV-3305] change to install latest INC & TF, add metric in fit
  examples/notebook/tensorflow/alexnet_mnist/conda_set_env.sh
  examples/notebook/tensorflow/alexnet_mnist/devcloud_setup_env.sh
  examples/notebook/tensorflow/alexnet_mnist/inc_quantize_model.py
  examples/notebook/tensorflow/alexnet_mnist/inc_sample_for_tensorflow.ipynb
  examples/notebook/tensorflow/alexnet_mnist/pip_set_env.sh
  examples/notebook/tensorflow/alexnet_mnist/requirements.txt
  examples/notebook/tensorflow/alexnet_mnist/run_in_intel_devcloud.sh
  examples/notebook/tensorflow/alexnet_mnist/run_jupyter.sh
  examples/notebook/tensorflow/alexnet_mnist/run_sample.sh
Labels: bug fix

#1525 Set model to `training` mode before accelerate prepare
  examples/pytorch/nlp/huggingface_models/question-answering/pruning/eager/run_qa_no_trainer.py
Labels: bug fix

#1514 Fix wrong socket number retrieval for non-english system
  neural_compressor/utils/utility.py
Labels: enhancement

#1519 fix model url, adapt to inc api
  examples/notebook/tensorflow/vgg19_ibean/inc_quantize_vgg19.ipynb
Labels: bug fix

#1543 Add Config Registry for autotune
  neural_compressor/common/base_config.py
  neural_compressor/tensorflow/quantization/config.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils/constants.py
Labels: INC3.X

#1541 Fix Keras Deserialization Issue of Lambda Layers
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  docs/source/releases_info.md
  neural_compressor/adaptor/keras.py
  neural_compressor/tensorflow/algorithms/static_quantize/keras.py
Labels: bug fix

#1464 Add PTQ example for PyTorch CV - Segment Anything Model
  examples/pytorch/image_recognition/segment_anything/README.md
  examples/pytorch/image_recognition/segment_anything/download_dataset.py
  examples/pytorch/image_recognition/segment_anything/inc_dataset_loader.py
  examples/pytorch/image_recognition/segment_anything/main.py
  examples/pytorch/image_recognition/segment_anything/requirements.txt
  examples/pytorch/image_recognition/segment_anything/run_benchmark.sh
  examples/pytorch/image_recognition/segment_anything/run_quant.sh
Labels: examples, extension test

#1542 Stop the tuning process early when enabling smooth quant
  neural_compressor/strategy/strategy.py
  test/algorithm/test_smooth_quant.py
Labels: bug fix, extension test

#1528 Refactor the tuning pipeline
  neural_compressor/common/base_tune.py
  neural_compressor/common/base_tuning.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/autotune.py
  neural_compressor/torch/tune.py
  test/3x/torch/test_autotune.py
Labels: INC3.X, Auto-Tune

#1526 Fix ONNXRT calibration for Dml EP
  neural_compressor/adaptor/onnxrt.py
  neural_compressor/adaptor/ox_utils/calibration.py
  test/adaptor/onnxrt_adaptor/test_onnxrt_augment.py
Labels: bug fix

#1553 Add default workspace for 3.x
  neural_compressor/common/__init__.py
  neural_compressor/common/base_config.py
  neural_compressor/common/base_tuning.py
  neural_compressor/common/utils/__init__.py
  neural_compressor/common/utils/constants.py
  neural_compressor/common/utils/logger.py
  neural_compressor/common/utils/utility.py
  neural_compressor/tensorflow/algorithms/static_quantize/keras.py
  neural_compressor/tensorflow/algorithms/static_quantize/quantize_entry.py
  neural_compressor/tensorflow/quantization/config.py
  neural_compressor/tensorflow/quantization/quantize.py
  neural_compressor/torch/algorithms/weight_only/gptq.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
  neural_compressor/torch/algorithms/weight_only_algos.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/fp8/quantization_impl.py
  neural_compressor/torch/quantization/layers.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils/utility.py
  test/3x/tensorflow/test_config.py
  test/3x/torch/quantization/weight_only/test_gptq_algo.py
  test/3x/torch/quantization/weight_only/test_rtn.py
  test/3x/torch/test_autotune.py
  test/3x/torch/test_config.py
  test/3x/torch/test_utils.py
Labels: INC3.X

#1559 Fix common import for onnxrt
  neural_compressor/onnxrt/algorithms/weight_only/algo_entry.py
  neural_compressor/onnxrt/quantization/config.py
  neural_compressor/onnxrt/quantization/quantize.py
  neural_compressor/onnxrt/utils/onnx_model.py
  neural_compressor/onnxrt/utils/utility.py
  test/3x/onnxrt/quantization/weight_only/test_rtn.py
  test/3x/onnxrt/test_config.py
Labels: INC3.X

#1515 Use scm version
  .gitignore
  setup.py
Labels: enhancement

#1562 Add default config set for tuning
  neural_compressor/common/base_config.py
  neural_compressor/common/base_tuning.py
  neural_compressor/onnxrt/quantization/config.py
  neural_compressor/tensorflow/quantization/config.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/quantization/config.py
  test/3x/onnxrt/test_config.py
  test/3x/tensorflow/test_config.py
  test/3x/torch/test_autotune.py
Labels: INC3.X, Auto-Tune

#1581 Unify the `logger` usage
  .azure-pipelines/scripts/ut/3x/collect_log_3x.sh
  neural_compressor/common/__init__.py
  neural_compressor/common/base_config.py
  neural_compressor/common/base_tuning.py
  neural_compressor/common/utils/logger.py
  neural_compressor/onnxrt/algorithms/weight_only/algo_entry.py
  neural_compressor/onnxrt/quantization/config.py
  neural_compressor/onnxrt/quantization/quantize.py
  neural_compressor/onnxrt/utils/onnx_model.py
  neural_compressor/onnxrt/utils/utility.py
  neural_compressor/tensorflow/algorithms/static_quantize/keras.py
  neural_compressor/tensorflow/quantization/quantize.py
  neural_compressor/torch/algorithms/weight_only_algos.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/quantization/layers.py
  neural_compressor/torch/quantization/quantize.py
  neural_compressor/torch/utils/utility.py
  test/3x/onnxrt/quantization/weight_only/test_rtn.py
  test/3x/onnxrt/test_config.py
  test/3x/tensorflow/test_config.py
  test/3x/torch/quantization/weight_only/test_gptq_algo.py
  test/3x/torch/quantization/weight_only/test_rtn.py
  test/3x/torch/test_autotune.py
  test/3x/torch/test_config.py
  test/3x/torch/test_logger.py
  test/3x/torch/test_utils.py
Labels: INC3.X

#1579 Add `tolerable_loss` to `TuningConfig`
  neural_compressor/common/base_tuning.py
  neural_compressor/torch/quantization/autotune.py
  test/3x/common/test_common.py
  test/3x/common/test_utility.py
  test/3x/torch/test_autotune.py
Labels: INC3.X, Auto-Tune

#1583 Fix logger
  .azure-pipelines/scripts/ut/3x/run_3x_pt.sh
  docs/source/adaptor.md
  docs/source/migration.md
  docs/source/pruning.md
  docs/source/quantization.md
  docs/source/tuning_strategies.md
  neural_compressor/common/__init__.py
  neural_compressor/common/utils/logger.py
  neural_compressor/compression/pruner/README.md
  neural_compressor/torch/quantization/modules.py
  test/3x/common/test_logger.py
  test/3x/torch/test_logger.py
Labels: INC3.X, module: common
