Repository intel/neural-compressor, pull requests merged in 2024-07, with the labels that each got.

#1886 Remove Gelu Fusion for TF Newapi
  neural_compressor/tensorflow/quantization/utils/graph_rewriter/generic/fuse_gelu.py
  test/3x/tensorflow/quantization/ptq/newapi/test_graph_fuse_gelu_newapi.py
Labels: bug fix, INC3.X, TensorFlow

#1888 Refine HQQ UTs
  test/3x/torch/quantization/weight_only/hqq/test_hqq_cuda.py
  test/3x/torch/quantization/weight_only/test_hqq.py
Labels: INC3.X, PyTorch

#1895 Port auto-detect absorb layers for TEQ
  neural_compressor/torch/algorithms/weight_only/teq.py
  test/3x/torch/algorithms/weight_only/test_teq_quantizer.py
Labels: INC3.X, PyTorch

#1904 Get default config based on the auto-detect CPU type
  neural_compressor/common/utils/constants.py
  neural_compressor/common/utils/utility.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/utils/utility.py
  test/3x/common/test_utility.py
  test/3x/torch/test_config.py
Labels: INC3.X, PyTorch

#1918 Support PT2E save and load
  neural_compressor/torch/algorithms/pt2e_quant/__init__.py
  neural_compressor/torch/algorithms/pt2e_quant/save_load.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/load_entry.py
  test/3x/torch/quantization/test_pt2e_quant.py
Labels: INC3.X, PyTorch

#1924 Fix a typo in architecture diagram
  docs/3x/imgs/architecture.png
Labels: documentation

#1883 Support LayerWise for RTN/GPTQ
  .azure-pipelines/scripts/codeScan/pylint/pylint.sh
  neural_compressor/torch/algorithms/layer_wise/load.py
  neural_compressor/torch/algorithms/layer_wise/utils.py
  neural_compressor/torch/algorithms/weight_only/gptq.py
  neural_compressor/torch/algorithms/weight_only/modules.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/utils/__init__.py
  requirements_pt.txt
  test/3x/torch/algorithms/weight_only/test_woq_module.py
  test/3x/torch/quantization/weight_only/test_gptq.py
  test/3x/torch/quantization/weight_only/test_rtn.py
Labels: INC3.X, PyTorch

#1925 Integrate AutoRound v0.3
  neural_compressor/torch/algorithms/weight_only/autoround.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  test/3x/torch/quantization/weight_only/test_autoround.py
  test/3x/torch/requirements.txt
Labels: INC3.X

#1914 Add doc for client usage
  README.md
  docs/3x/PT_WeightOnlyQuant.md
  docs/3x/client_quant.md
Labels: documentation

#1931 Fix unused pkgs import
  neural_compressor/torch/algorithms/layer_wise/utils.py
  neural_compressor/torch/utils/__init__.py
  neural_compressor/torch/utils/utility.py
Labels: PyTorch

#1882 Update Example for Pytorch 3x Mixed Precision
  docs/3x/PT_MixedPrecision.md
  examples/.config/model_params_pytorch_3x.json
  examples/3.x_api/pytorch/cv/mixed_precision/README.md
  examples/3.x_api/pytorch/cv/mixed_precision/main.py
  examples/3.x_api/pytorch/cv/mixed_precision/requirements.txt
  examples/3.x_api/pytorch/cv/mixed_precision/run_autotune.sh
  examples/3.x_api/pytorch/cv/mixed_precision/run_benchmark.sh
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/README.md
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/main.py
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/requirements.txt
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/run_benchmark.sh
  neural_compressor/common/utils/constants.py
  neural_compressor/torch/algorithms/mixed_precision/__init__.py
  neural_compressor/torch/algorithms/mixed_precision/half_precision_convert.py
  neural_compressor/torch/algorithms/mixed_precision/module_wrappers.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  test/3x/torch/test_autotune.py
Labels: examples, INC3.X, PyTorch

#1938 Add docstring for WOQ&LayerWise
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  neural_compressor/torch/algorithms/layer_wise/load.py
  neural_compressor/torch/algorithms/layer_wise/modified_pickle.py
  neural_compressor/torch/algorithms/layer_wise/utils.py
  neural_compressor/torch/algorithms/weight_only/__init__.py
  neural_compressor/torch/algorithms/weight_only/autoround.py
  neural_compressor/torch/algorithms/weight_only/awq.py
  neural_compressor/torch/algorithms/weight_only/gptq.py
  neural_compressor/torch/algorithms/weight_only/modules.py
  neural_compressor/torch/algorithms/weight_only/rtn.py
  neural_compressor/torch/algorithms/weight_only/save_load.py
  neural_compressor/torch/algorithms/weight_only/teq.py
  neural_compressor/torch/algorithms/weight_only/utility.py
  neural_compressor/torch/quantization/config.py
Labels: PyTorch

#1940 Update for API 3.0 online doc
  README.md
  docs/3x/get_started.md
  docs/build_docs/build.sh
  docs/source/3x/PT_DynamicQuant.md
  docs/source/3x/PT_MXQuant.md
  docs/source/3x/PT_MixedPrecision.md
  docs/source/3x/PT_SmoothQuant.md
  docs/source/3x/PT_StaticQuant.md
  docs/source/3x/PT_WeightOnlyQuant.md
  docs/source/3x/PyTorch.md
  docs/source/3x/TF_Quant.md
  docs/source/3x/TF_SQ.md
  docs/source/3x/TensorFlow.md
  docs/source/3x/autotune.md
  docs/source/3x/benchmark.md
  docs/source/3x/design.md
  docs/source/3x/imgs/architecture.png
  docs/source/3x/imgs/data_format.png
  docs/source/3x/imgs/mx_workflow.png
  docs/source/3x/imgs/smoothquant.png
  docs/source/3x/imgs/sq_convert.png
  docs/source/3x/imgs/sq_pc.png
  docs/source/3x/imgs/workflow.png
  docs/source/3x/llm_recipes.md
  docs/source/3x/quantization.md
  docs/source/api-doc/api_2.rst
  docs/source/api-doc/api_3.rst
  docs/source/api-doc/apis.rst
  docs/source/api-doc/tf_quantization_autotune.rst
  docs/source/api-doc/tf_quantization_common.rst
  docs/source/api-doc/tf_quantization_config.rst
  docs/source/api-doc/torch_quantization_autotune.rst
  docs/source/api-doc/torch_quantization_common.rst
  docs/source/api-doc/torch_quantization_config.rst
  docs/source/get_started.md
  neural_compressor/tensorflow/__init__.py
  neural_compressor/tensorflow/quantization/__init__.py
  neural_compressor/tensorflow/quantization/autotune.py
  neural_compressor/tensorflow/quantization/config.py
  neural_compressor/tensorflow/quantization/quantize.py
  neural_compressor/torch/__init__.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/quantization/quantize.py
Labels: documentation

#1946 Refine Pytorch 3x Mixed Precision Example
  examples/.config/model_params_pytorch_3x.json
  examples/3.x_api/pytorch/cv/mixed_precision/README.md
  examples/3.x_api/pytorch/cv/mixed_precision/run_benchmark.sh
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/README.md
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/main.py
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/requirements.txt
  examples/3.x_api/pytorch/image_recognition/torchvision_models/mixed_precision/resnet18/run_benchmark.sh
Labels: INC3.X, PyTorch

#1947 Update doc for client-usage and LWQ
  README.md
  docs/source/3x/PT_WeightOnlyQuant.md
  docs/source/3x/client_quant.md
  docs/source/3x/imgs/lwq.png
Labels: documentation

#1944 Add Docstring for TF 3x API and Torch 3x Mixed Precision
  .azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt
  docs/source/3x/TensorFlow.md
  neural_compressor/tensorflow/algorithms/__init__.py
  neural_compressor/tensorflow/algorithms/smoother/__init__.py
  neural_compressor/tensorflow/algorithms/smoother/core.py
  neural_compressor/tensorflow/algorithms/static_quant/__init__.py
  neural_compressor/tensorflow/algorithms/static_quant/keras.py
  neural_compressor/tensorflow/keras/__init__.py
  neural_compressor/tensorflow/keras/layers/__init__.py
  neural_compressor/tensorflow/keras/layers/conv2d.py
  neural_compressor/tensorflow/keras/layers/dense.py
  neural_compressor/tensorflow/keras/layers/depthwise_conv2d.py
  neural_compressor/tensorflow/keras/layers/layer_initializer.py
  neural_compressor/tensorflow/keras/layers/pool2d.py
  neural_compressor/tensorflow/keras/layers/separable_conv2d.py
  neural_compressor/tensorflow/keras/quantization/__init__.py
  neural_compressor/tensorflow/keras/quantization/config.py
  neural_compressor/tensorflow/quantization/algorithm_entry.py
  neural_compressor/tensorflow/quantization/autotune.py
  neural_compressor/tensorflow/quantization/config.py
  neural_compressor/tensorflow/quantization/quantize.py
  neural_compressor/tensorflow/quantization/utils/__init__.py
  neural_compressor/tensorflow/quantization/utils/graph_rewriter/__init__.py
  neural_compressor/tensorflow/utils/__init__.py
  neural_compressor/tensorflow/utils/constants.py
  neural_compressor/tensorflow/utils/model.py
  neural_compressor/tensorflow/utils/model_wrappers.py
  neural_compressor/tensorflow/utils/utility.py
  neural_compressor/torch/algorithms/mixed_precision/__init__.py
  neural_compressor/torch/quantization/config.py
Labels: INC3.X, PyTorch, TensorFlow

#1945 Complement UT of calibration function for TF 3x API
  .azure-pipelines/scripts/ut/3x/run_3x_tf.sh
  test/3x/tensorflow/test_quantize_model.py
Labels: INC3.X, TensorFlow

#1943 Enable yolov5 Example for TF 3x API
  examples/.config/model_params_tensorflow_3x.json
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/README.md
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/main.py
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/prepare_dataset.sh
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/prepare_model.sh
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/requirements.txt
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/run_benchmark.sh
  examples/3.x_api/tensorflow/object_detection/yolo_v5/quantization/ptq/run_quant.sh
Labels: INC3.X, TensorFlow
