Repository intel/neural-compressor, pull requests merged in 2024-12, with the labels that each got.

#2082 Fixed the PT2E LLM example
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/README.md
  examples/3.x_api/pytorch/nlp/huggingface_models/language-modeling/quantization/static_quant/pt2e/run_clm_no_trainer.py
Labels: bug fix, PyTorch, PT2E

#2085 [Document] Add mapping for v3.2 to Gaudi SW stack v1.19
  docs/source/3x/gaudi_version_map.md
Labels: documentation

#2094 Fix `is_sharded` setting for loading quant model
  neural_compressor/torch/algorithms/weight_only/save_load.py
Labels: bug fix, Related to 1.19.0
