Repository intel/neural-compressor, pull requests merged in 2024-03, with the labels that each got.

#1640 CI workflow optimize for summary
  .azure-pipelines/code-scan-neural-insights.yaml
  .azure-pipelines/code-scan-neural-solution.yaml
  .azure-pipelines/code-scan.yml
  .azure-pipelines/scripts/ut/3x/collect_log_3x.sh
  .azure-pipelines/scripts/ut/3x/run_3x_ort.sh
  .azure-pipelines/scripts/ut/3x/run_3x_pt.sh
  .azure-pipelines/scripts/ut/3x/run_3x_tf.sh
  .azure-pipelines/scripts/ut/collect_log.sh
  .azure-pipelines/scripts/ut/compare_coverage.sh
  .azure-pipelines/scripts/ut/run_basic_adaptor.sh
  .azure-pipelines/scripts/ut/run_basic_adaptor_tfnewapi.sh
  .azure-pipelines/scripts/ut/run_basic_api.sh
  .azure-pipelines/scripts/ut/run_basic_itex.sh
  .azure-pipelines/scripts/ut/run_basic_others.sh
  .azure-pipelines/scripts/ut/run_basic_pt_pruning.sh
  .azure-pipelines/scripts/ut/run_basic_tf_pruning.sh
  .azure-pipelines/template/code-scan-template.yml
  .azure-pipelines/template/docker-template.yml
  .azure-pipelines/template/ut-template.yml
  .azure-pipelines/ut-3x-ort.yml
  .azure-pipelines/ut-3x-pt.yml
  .azure-pipelines/ut-3x-tf.yml
  .azure-pipelines/ut-basic-no-cover.yml
  .azure-pipelines/ut-basic.yml
  .azure-pipelines/ut-itrex.yml
  .azure-pipelines/ut-ncoder.yml
  .azure-pipelines/ut-neural-insights.yaml
  .azure-pipelines/ut-neural-solution.yaml
  .pre-commit-config.yaml
Labels: WIP

#1641 Enable autoround export [2.x]
  .azure-pipelines/scripts/ut/env_setup.sh
  neural_compressor/adaptor/pytorch.py
  neural_compressor/adaptor/torch_utils/weight_only.py
  test/adaptor/pytorch_adaptor/test_weight_only_adaptor_pytorch.py
  test/quantization/test_weight_only_quantization.py
  test/requirements.txt
Labels: WIP

#1644 Fix onnxrt llama example
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/ptq_static/main.py
  examples/onnxrt/nlp/huggingface_model/text_generation/llama/quantization/weight_only/main.py
Labels: bug fix, examples

#1655 Refine code and update `autotune` API
  neural_compressor/common/base_config.py
  neural_compressor/common/base_tuning.py
  neural_compressor/common/tuning_param.py
  neural_compressor/onnxrt/quantization/autotune.py
  neural_compressor/tensorflow/quantization/autotune.py
  neural_compressor/torch/quantization/autotune.py
  neural_compressor/torch/utils/utility.py
  test/3x/common/test_common.py
  test/3x/onnxrt/test_autotune.py
  test/3x/tensorflow/test_autotune.py
  test/3x/torch/quantization/weight_only/test_mixed_algos.py
  test/3x/torch/quantization/weight_only/test_woq_on_cuda.py
  test/3x/torch/test_autotune.py
Labels: INC3.X

#1658 Fix onnxrt example bug: bart export failure
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_dynamic/requirements.txt
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/prepare_model.py
  examples/onnxrt/nlp/huggingface_model/text_classification/quantization/ptq_static/requirements.txt
Labels: bug fix, examples

#1647 Integrate Auto-Round to INC 3.x
  neural_compressor/common/utils/constants.py
  neural_compressor/torch/algorithms/weight_only/__init__.py
  neural_compressor/torch/algorithms/weight_only/autoround.py
  neural_compressor/torch/quantization/__init__.py
  neural_compressor/torch/quantization/algorithm_entry.py
  neural_compressor/torch/quantization/config.py
  neural_compressor/torch/utils/constants.py
  requirements_pt.txt
  test/3x/torch/quantization/weight_only/test_autoround.py
  test/3x/torch/requirements.txt
  test/3x/torch/test_config.py
  test/requirements.txt
Labels: INC3.X, PyTorch

#1671 Fix comparison of module_type and MulLinear
  neural_compressor/utils/pytorch.py
Labels: PyTorch

#1670 Update the readme
  README.md
Labels: documentation

#1674 Fixed the auto device detection
  neural_compressor/torch/utils/environ.py
  test/3x/torch/test_auto_accelerator.py
Labels: PyTorch

#1676 Add two torch examples
  examples/README.md
  examples/helloworld/README.md
  examples/helloworld/torch_static_quant/README.md
  examples/helloworld/torch_static_quant/quant_resnet18.py
  examples/helloworld/torch_static_quant/requirements.txt
  examples/helloworld/torch_woq/README.md
  examples/helloworld/torch_woq/quant_mistral.py
  examples/helloworld/torch_woq/requirements.txt
Labels: examples, PyTorch

#1686 Fix onnxrt split op
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlm/quantization/ptq_dynamic/main.py
  examples/onnxrt/nlp/huggingface_model/token_classification/layoutlm/quantization/ptq_static/main.py
  neural_compressor/adaptor/ox_utils/operators/split.py
Labels: bug fix

#1698 Refactor Keras PTQ Implementation
  neural_compressor/tensorflow/algorithms/static_quant/keras.py
  neural_compressor/tensorflow/keras/layers/__init__.py
  neural_compressor/tensorflow/keras/layers/conv2d.py
  neural_compressor/tensorflow/keras/layers/dense.py
  neural_compressor/tensorflow/keras/layers/depthwise_conv2d.py
  neural_compressor/tensorflow/keras/layers/layer_initializer.py
  neural_compressor/tensorflow/keras/layers/pool2d.py
  neural_compressor/tensorflow/keras/layers/quantizer.py
  neural_compressor/tensorflow/keras/layers/separable_conv2d.py
  neural_compressor/tensorflow/keras/quantization/config.py
  requirements_tf.txt
  test/3x/tensorflow/keras/test_config.py
  test/3x/tensorflow/quantization/test_smooth_quant.py
  test/3x/tensorflow/test_autotune.py
Labels: INC3.X, TensorFlow
